socallinuxexpo/scale-network

- README.md
Adding more info and some of the pkg requirements that will be needed to use this repo
Relates to https://github.com/socallinuxexpo/scale-network/pull/1
@irabinovitch @hriday let me know what you think!
> Updating the readme with reqs and contrib

- .gitattributes
- .gitignore
Adding more files that should be ignored and enabled `git lfs` for `.pdfs`.
@irabinovitch @hriday let me know what you think!
> Initial gitconfigs

- .github/PULL_REQUEST_TEMPLATE.md
- .gitignore
- CONTRIBUTING.md
- README.md
Adding the first draft of the contributing and PR docs. I'd wait to merge this until after the call tomorrow, 12/15. I'd like to see if anyone of the tech team has suggestions for either doc.
This PR also includes a better gitignore  generated using gitignore.io
@irabinovitch @owendelong @hriday
> Contributing and PR Docs

- switch-configuration/README.md
- switch-configuration/config/types/cfIDF
- switch-configuration/config/types/cfRoom
- switch-configuration/config/types/exIDF
- switch-configuration/config/types/exRoom
- switch-configuration/config/types/expo
- switch-configuration/config/types/hall
- switch-configuration/config/types/registration
- switch-configuration/config/vlans.d/Conference
- switch-configuration/config/vlans.d/Expo
> More config file progress.

- switch-configuration/README.md
Updating Switch README for firmware
How to get the latest firmware for juniper switches
@owendelong load these images on some of the switches
> [READY] Updating Switch README for firmware

- switch-configuration/MANUAL_SWITCH_SETUP.txt
- switch-configuration/README.md
- switch-configuration/config/types/cfRoom
- switch-configuration/config/types/exRoom
- switch-configuration/config/vlans.d/Bridged
- switch-configuration/config/vlans.d/Conference
- switch-configuration/config/vlans.d/Expo
- switch-configuration/todo
More progress -- IP addresses, Switch Manual Configuration Process, etc.
It floated with the wood and is therefore a duck.
> Owen v0.0.3

- switch-configuration/MANUAL_SWITCH_SETUP.txt
Improvements to manual switch process
Monkeys flinging pooh
Orangutangs flinging pooh
Tests? Tests? We don' need no steenkin' tests.
> Fixed MANUAL switch setup steps

- pi/gold_image.txt
Pi gold image instructions and todo list
Less structured documentation
More structured documentation
On a Pi2
> Pi gold image

- openwrt/README.md
- openwrt/files/root/bin/wifi-details.sh
Update the openwrt docs and fixes in the wifi script
Old docs and issue with script
update the openwrt and script
for the script i didnt have AP in front of me so tested locally with random dirs
> [READY] Update docs openwrt and script changes

- switch-configuration/config/scripts/switch_template.pl
- switch-configuration/config/types/exIDF
Fix
Generated configurations that couldn't be committed
Configurations can now be committed (and probably should be)
We had multiple inmates test these configurations at various assylums
> Fixed some bugs in template generator

- facts/pi/gold_image.txt
- switch-configuration/config/vlans.d/Bridged
changed tabs on cogent vlan, updated pi instructions.
pis didn't have unique hostnames
pis generate unique names
live with pis and by running inventory.py [tab check]
> [READY] pi adds + change tabs vlans

- switch-configuration/config/scripts/build_switch_configs.pl
- switch-configuration/config/scripts/switch_template.pl
> Fixed SNMP, Syslog, Root password

- switch-configuration/config/vlans.d/Expo
Fucking Paypal!!
Fucking Paypal didn't work on IPv6
Fucking Paypal might work on IPv4
Registrations couldn't pay.
> Fucking Paypal!!

- switch-configuration/config/types/registration
Adding correct vlan trunks for ap regdesk
Vlans now from 8-15 and infra vlan
Loaded on the config
> Adding correct vlan trunks for ap regdesk

- switch-configuration/config/types/Booth
Adding exstaff to expo
No exstaff vlan
exstaff vlan exists
Loaded to all expo switch
> [READY] Adding exstaff to expo

- CONTRIBUTING.md
Modifications to CONTRIBUTING document capturing the optional [WAIT] and [READY] workflow for PRs.
PRs with a title including [WAIT] were informally used to gate PRs which are work in progress. No formal documentation around this workflow.
Contributing document updated to capture the [WAIT] / [READY] optional PR workflow process.
Documentation only.
> [READY] reflect optional PR workflow

- ansible/inventory.py
Modification to `inventory.py` to support parsing VVRNG and dynamically generating VLAN information for the range specified. Documented in #144 . The change isn't the greatest way to handle this long term but was done in such a way to limit changes across other parts of the script. It's basically a feature flag around the directive so all non-VVRNG code paths remain effectively unchanged and any errors can be found in a single place. An overhaul of this functionality should be tackled as part of #149 .
Skipped VVRNG lines when parsing vlans.d files as that concept didn't exist until two days ago.
Using the range and supernets specified in the VVRNG line simply calculate all possible values in the range and create our standard vlan dictionary for them and stick them in vlans dictionary so …
> [READY] Handle VLAN or VVRNG directives

- switch-configuration/config/types/Booth
- switch-configuration/config/types/Catwalk
- switch-configuration/config/types/cfAV
- switch-configuration/config/types/cfIDF
- switch-configuration/config/types/cfRoom
- switch-configuration/config/types/exIDF
- switch-configuration/config/types/exRoom
- switch-configuration/config/types/registration
Remove DWCC remnants from switch configuration files
> Remove DWCC from remaining configs

- switch-configuration/README.md
> Updated README instructions for switch config load

- switch-configuration/config/scripts/switch_template.pl
> Fixed issue #167

- switch-configuration/config/scripts/switch_template.pl
> Fixes issue #169

- switch-configuration/config/scripts/switch_template.pl
Fixes documented in issue #171
> Fixes documented in issue #171

- switch-configuration/config/types/cfAV
> Add cfAVLAN to AP ports on cfAV switch

- switch-configuration/config/switchtypes
Also added data about hierarchy to comments for automated ping testing.
> Fixed #196/#197

- switch-configuration/config/types/cfAV
adds ports to support AP and sign inside conference room door
av ports
wireless and sign ports
n/a
> adds ports to support AP and sign inside conference room door

- openwrt/files/etc/zabbix_agentd.conf
- tests/unit/openwrt/golden/ar71xx/etc/zabbix_agentd.conf
- tests/unit/openwrt/golden/ipq806x/etc/zabbix_agentd.conf
several tweaks
live on the show
> update zabbix_agent.conf to support higher loads

- ansible/etc/ansible/roles/zabbixagent/defaults/main.yml
- ansible/etc/ansible/roles/zabbixagent/handlers/main.yml
- ansible/etc/ansible/roles/zabbixagent/tasks/main.yml
- ansible/etc/ansible/roles/zabbixagent/templates/zabbix_agentd.conf.j2
- ansible/etc/ansible/scale.yml
Simple Zabbix agent role
No automated zabbix agent install for servers
Zabbix agent installed on servers
Live!
> [READY] Zabbix Agent

- switch-configuration/config/scripts/switch_template.pl
Deployed on switches and working.
> Added Vlan 103 to OSPF3 for vendor vlans to transit

- monitoring/zabbix_server.conf
The current zabbix_server.conf on zabbix_server.conf.
Will be updating as config chenges
Tracking changes to zabbix_server.conf
Was not currently pushing th github
Will currently track any and all chenges
Will report changes
> zabbix_server.conf on Sun Mar 10 02:04:32 UTC 2019

- README.md
Adding scale logo to the toplevel README.md
No logo
* Adding scale logo to toplevel readme
* Validated that formatting in README.md looks good
> [READY]: Adding ref to scale tech tux

- .github/ISSUE_TEMPLATE.md
I like the format of the issues @sarcasticadmin has been opening lately with acceptance criteria. This PR adds a similar format as an issue template. This doesn't have to be the final format but I wanted to just get something going to start the discussion. Please feel free to take it from here and modify it in flight.
I don't know how to test this without pushing to master. I used this github blog article to verify correct filename and location https://github.blog/2016-02-17-issue-and-pull-request-templates/
> [READY] Add an Issue template

- .kermit/README.md
- .kermit/bhyve.kermit
- README.md
- ansible/README.md
- ansible/roles/bhyve/README.md
- ansible/roles/bhyve/files/scale-signs.conf
- ansible/roles/bhyve/files/scale-zabbix.conf
Relates to: #268 
With these docs the servers for running our VMs are configured and correctly 
* No server hardware existed
* kermit configuration for bhyve servers
* VM configuration templates for bhyve
* Documentation for byhve server configuration
Configured one server to create these instructions
> [READY] issue-268 - Adding bhyve configuration and docs

- switch-configuration/config/WallJackList
Store Wall Jack list obtained from SCaLE17x in Repo
N/A documentation only
> [READY] Add Jack List

- facts/pi/gold_image.txt
- facts/pi/scripts/reg.py
- facts/pi/scripts/web.py
Fixes #256 
Only had pi4 images for "imaging" and "general" pis, none for registration / signs.
Have pi4 images for registration / signs. Instructions added.
Building pis at work party. Having David and Peter try to do nefarious things. Creating compressed image.
> [READY] add new signs/reg image instructions for pi4

- openwrt/TPLINK.md
- openwrt/scripts/local/dhcpd_net.sh
Part of: #279 
Fixes the flashing process for ipq806x and adds dhcpd script for freebsd to easily test
* Flashing instructions only on freebsd for ipq806x
* Flashing instructions on linux for ipq806x
* Adding dhcpd script
* Ran documentation
> [READY] issue-279 - Flashing docs for ipq806x and script

- facts/pi/gold_image.md
- facts/pi/gold_image.txt
Clarifies Raspbian version and eliminate reference to older version of Raspbian.
Adds mechanism for specifying future versions without losing track of previous specified versions.
Documentation only -- N/A
> Fix reference to Rapsbian version.

- switch-configuration/config/types/cfIDF
Add port for server to Conf IDF switch
> Added port to ConfIDF for server

- switch-configuration/config/scripts/switch_pinger
- switch-configuration/config/types/cfIDF
Added AV and Infra ports for servers on cfIDF switch -- not used,
servers plugged into routers.
> Fixed switch_pinger for newer version of ping (-o switch removed).

- switch-configuration/config/scripts/override_switches
- switch-configuration/config/scripts/switch_template.pl
Created override_switches to load new configuration files
Updated switch_template.pl to fix some bugs related to override_switches and update_switches
> Created override_switches to load new configs

- switch-configuration/config/switchtypes
Renumbered CTF management addresses
> [READY] Renumbered CTF management addresses

- switch-configuration/config/scripts/switch_template.pl
value in tuple.
Fixes #313 
Bad configuration files per #313 
Valid configuration files
Generated new configurations and inspected manually
> Updated remaining calls to get_switchtype to reflect additional return

- switch-configuration/config/scripts/switch_pinger
Resolves #316 
Pinger reported incorrect results and had excessive delay on linux
Pinger works correctly on both linux and Mac
Ran program, validated results manually.
> Resolves #316

- switch-configuration/config/scripts/switch_template.pl
> Added interface name to LLDP data

- openwrt/scripts/local/ap_command.sh
- openwrt/scripts/local/update-resolv.conf.sh
Adding two scripts for ping and commanding the aps
* A script in `openwrt/scripts/local`
* used to apply changes in the show
> [READY] Adding existing script for adhoc AP changes

- .kermit/juniper.kermit
- ansible/README.md
- shell.nix
For a discussion and intro of nixpkgs into scale-network
- No kermit config
- No shell.nix
- Kermit config for junipers
- shell.nix with basic tools
> [READY] - nix-shell and kermit configs

- MAPS.md
Fixes: #423 
Adding new layout/maps for LAX Hilton
- Only had layout for pasadena
- Layouts for both venues now
- Markdown renders
> [READY] - Updating MAPS.md with LAX hilton refs

- MAPS.md
Fixes: #423
Adding 2nd wave of hilton venue pdfs to our collection, thanks @irabinovitch !
- Adding 3 more hilton venue pdfs being served from s3
- Ensure all links work as expected
> [READY] - Adding second wave for hilton venue pdfs

- openwrt/display/usb_display/128x32OLED_SCaLE_AP.ino
Relates to: https://github.com/socallinuxexpo/scale-network/issues/351
Working text version, 3 formats and blink.
See code for documentation. Will add README later.
This project may or may not get picked back up later. Merging the code into master so it's not a dangling lost branch.
It wasn't.
> [READY] - Initial commit of Arduino code for AP USB Displays

- switch-configuration/config/.gitignore
- switch-configuration/config/scripts/generate_ps_stickers.pl
- switch-configuration/config/switchtypes
- switch-configuration/config/types/hiIDF
Working Vinyl Printer/Cutter Program
Bonus content: Cleaned up HiIDF type file (corrected unused port counts)
Added .gitignore file to ignore stickers.ps and stickers.pdf (files generated during sticker testing)
Script generated errant PostScript which didn't produce good stickers
Script now generates postscript which looks correct and PDF Preview looks good.
Ghostscript -> PDF -> Preview
> [READY] - Owen 19x pre.01

- router-configuration/to_push/br-mdf-01
- router-configuration/to_push/br-mdf-map.eps
- switch-configuration/config/scripts/generate_ps_stickers.pl
- switch-configuration/config/switchtypes
Several problems solved and other improvements in preparation for SCaLE 19x (Hilton LAX)
Stickers would print misaligned, No label for BR-MDF router, and incorrect hierarchy information for switches
Above issues are addressed.
Stickers were all printed and look correct, with proper cut alignment.
> [READY] - Owen 19x pre.03

- CONTRIBUTING.md
Adding more common scenarios to QA in CONTRIBUTING.md
- Only 1 QA item existed
- 3 QA items exist for common scenarios
- @owendelong to confirm
> [READY] - Adding more QA to CONTRIBUTING.md

- switch-configuration/Makefile
- switch-configuration/config/scripts/override_switches
- switch-configuration/config/types/hiMDF
- switch-configuration/config/vlans.d/Hilton
Trunk fixups
Makefile fixes
VLAN fixes
Trunk fixups
Makefile fixes
VLAN fixes
OOPS
Better
In progress
> [READY] - OOPS

- ansible/roles/bhyve/README.md
Docs were dated and from FreeBSD 12.1 and scale 18x
- FreeBSD 13.1 setup instructions for scale 19x
- Markdown looks good :slightly_smiling_face:
> [READY] - Updating notes for bhyve pre-19x

- switch-configuration/config/types/hiIDF
Various typo fixes and other minor tweaks to make network go.
I broke it.
I fixed it.
We are paxled... We need Jordi to make our ship go.
> [READY] - Additional fixes for vlan types in switch configs

- switch-configuration/config/types/hiRoom
Add Registration port to room switches (including San Lorenzo B)
No Registration ports in rooms.
Added two registration access ports to class hiRoom
No testing needed, simple VLAN add.
> issue 467 -- add reg to rooms

- switch-configuration/Makefile
- switch-configuration/config/scripts/bulk_local_load_switches
- switch-configuration/config/scripts/switch_pinger
- switch-configuration/config/switchtypes
- switch-configuration/config/types/hiAV
- switch-configuration/config/types/hiBooth
- switch-configuration/config/types/hiIDF
- switch-configuration/config/types/hiMDF
- switch-configuration/config/types/hiNOC
- switch-configuration/config/types/hiRegistration
- switch-configuration/config/types/hiRoom
Many changes, see commit logs
Stuff was different.
Stuff mostly works now and is as built SCaLE 19x.
Real world deployment... What could possibly go wrong?
> Owen 19x patch7

- switch-configuration/config/types/hiRoom
Recreating issue 467 changes
Changes got lost somehow
Reinstalled changes
No testing
> Recreating issue 467 changes

- facts/datasource.py
In function isvalidmodel(model) we can use a set for the enumeration, and the in operator returns a boolean (so just return model in ...)
Style/brevity change; no change in behavior
Tested in REPL
> use set; and in returns boolean

- facts/keys/dlang_id_ed25519.pub
> Additional public key for dlang (switch compatible)

- switch-configuration/Makefile
- switch-configuration/config/scripts/build_switch_configs.pl
- switch-configuration/config/scripts/bulk_local_load_switches
- switch-configuration/config/scripts/override_switches
- switch-configuration/config/scripts/switch_template.pl
- switch-configuration/config/switchtypes
- switch-configuration/config/types/Booth
- switch-configuration/config/types/hiAV
- switch-configuration/config/types/hiBooth
- switch-configuration/config/types/hiIDF
- switch-configuration/config/types/hiMDF
- switch-configuration/config/types/hiNOC
- switch-configuration/config/types/hiRegistration
- switch-configuration/config/types/hiRoom
- switch-configuration/config/vlans.d/Expo
- switch-configuration/config/vlans.d/Hilton
Added missing dependency to Makefile
Added skip for unused switches to override_switches
Added sign switches for outside Expo
Multiple updates to support show realities
Trial by fire.
> [READY] Multiple updates

- switch-configuration/config/makemap
script that scrapes switch configs for lldp data and creates png and svg diagrams
> initial version of script to make topo from lldp

- openwrt/Makefile
- openwrt/configs/common.config
- openwrt/files/root/bin/apinger-pop.sh
- openwrt/scripts/local/net_loadtest.sh
- shell.nix
- tests/serverspec/spec/shared/openwrt/init.rb
- tests/unit/openwrt/golden/ar71xx/root/bin/apinger-pop.sh
- tests/unit/openwrt/golden/ipq806x/root/bin/apinger-pop.sh
Fixes: #513 
Updating our openwrt image to latest commit off `master`
- Previously set to a version of openwrt for 19x
- Running latest build of openwrt on supported hardware for 20x
- Leverage a temporary fork of opkgs
- Builds: https://github.com/socallinuxexpo/scale-network/actions/runs/3791195350
- Flashes against running hardware and all serverspec tests passing: https://gitlab.com/socallinuxexpo/scale-network/-/jobs/3531665684
- Client load test results: [results-1672250760.log](https://github.com/socallinuxexpo/scale-network/files/10315694/results-1672250760.log)
Speed summary from client results (only SUMs):
```
$ cat ~/Downloads/results-1672250760.log | grep SUM
[SUM]   0.00-1.00   sec  2.84 MBytes  23.8 Mbits/sec   79             
[SUM]   1.00-2.00   sec  2.42 MBytes  20.3 …
```
> [READY] - Bumping openwrt and opkg for 20x

- facts/keys/rhamel_id_ed25519.pub
Add Ryan Hamel's SSH key to access network equipment.
> Add Ryan Hamel Public SSH Key

- switch-configuration/config/scripts/bulk_local_load_switches
Added user option (-u)
No -u option
-u option
Patches? Patches? We don' need no steenkin' patches.
> Added user option (-u)

- switch-configuration/config/switchtypes
- Recreated minimal switch config "miniconfig" Bug fixes for bulk_local_load_switches
- Updated switchtypes with correct MAC addresses for 24 port switches
> owen 20x 08

- switch-configuration/config/scripts/switch_pinger
- switch-configuration/config/switchtypes
- Improved switch_pinger to skip hosts down hierarchy from down hosts Fixed daisy chain for CTF switches in switchtypes
> owen 20x 10

- nix/machines/core/common.nix
add git and vim to coreMaster and slaveMaster
git clone git@github.com:socallinuxexpo/scale-network.git
cd scale-network
nix repl
>>:lf .
>>:b nixosConfigurations.x86_64-linux.coreMaster.config.system.build.toplevel
>>:b nixosConfigurations.x86_64-linux.coreSlave.config.system.build.toplevel
> added git and vim to coreMaster coreSlave

- utilities/bhyve/README.md
The bhyve README.md contains quoting errors due to missing quote.  This commit adds the quote that fixes it.
Looks good to me in the Github.  If you agree, apply the pull request thanks.
> [READY] Fixed quotes in bhyve README.md

- switch-configuration/config/scripts/switch_pinger
- switch-configuration/config/switchtypes
- switch-configuration/config/types/exIDF
- Added PoE capability for access ports and improved PoE configuration mechanism
- Fixed bugs in switch_pinger Replaced switch5 (BallroomDE) with switch50 (SpareC) and name swaped in switchtypes Added additional IDF Switch Ports to NW-IDF (reduced AP Ports)
- Corrected an error in the SPARE swap in switchtypes
> od 20x p03

- nix/machines/core/master.nix
- nix/machines/signs.nix
- most updates to signs
- bump zone as well
> [READY] - New updates to signs

- facts/servers/serverlist.csv
- nix/machines/core/master.nix
- nix/machines/signs.nix
- bumping signs to fix syntax in rooms.php
- updating monitoring1 facts entry
> [READY] - updating monitoring1 entry and new signs release

- switch-configuration/config/types/cfIDF
- switch-configuration/config/types/exIDF
Unify IDF switch layouts
Radical differences in port layouts, added confusion, cats and dogs in the same room, chaos, despair.
Happy people.
Who tests stuff?
> Updated layout of IDF switches (CF and Ex) to unify port layout

- Makefile
Added a make file for common nix build targets #582
make show
make bhyveImage signs  (this will make the signs server)
We can test this in CI i suppose?
> makefile wrapper for issue #582

- .github/workflows/validate-datafiles.yml
Remove ansible-test from CI
Ansible validation was performed during CI.
Ansible validation is no longer performed during CI.
N/A
> [READY] Remove ansible-test from CI

- openwrt/README.md
- openwrt/docs/MT7622.md
Documenting our steps for recovery mode
- No steps for recovery mode for mt7662
- Docs for recovery mode
- Confirmed these steps on the linksys e8450
> [READY] - recovery mode steps

- facts/inventory.py
- nix/machines/monitor.nix
Adding a new function to the inventory script to generate a Prometheus config for the monitor nix machine
No Prometheus config generation
Prometheus config generation
nix build
> [READY] Generate prometheus config from inventory

- flake.lock
- flake.nix
- nix/machines/_common/base.nix
- nix/machines/_common/default.nix
- nix/machines/devServer/default.nix
- nix/machines/devServer/hardware-configuration.nix
- nix/machines/flake-module.nix
Relates to: #660
init the configuration of the `devServer` thats being hosted in northern california
- No dev server :/
- dev server for all kinds of fun
- base.nix for setting the bulk of base packages on our systems
- dev server booted and can `nixos-rebuild switch`
> [READY] - init devServer 

- switch-configuration/config/scripts/switch_template.pm
Improved trunk colors (visibility) for stickers
Dark colors
Lighter, less filling, same great taste
Trial by fire
> [READY] Improved trunk colors (visibility) for stickers

- graphics/21x T-Shirt Color.svg
- graphics/Tux Facing Troy 21x.svg
Final Color T-Shirt Graphics
No color T-Shirts for 21x
RGBCMYK
Blood, Breath, and Urine
> [READY] Added color T-Shirt graphics

- switch-configuration/config/scripts/switch_template.pm
- switch-configuration/config/types/cfNOC
- switch-configuration/config/types/exIDF
Fixes
Broken
Fixed
1. Wave dead cat
2. See what cat strikes
3. Fix those things
4. Lather, Rinse, Repeat
> Fixed FIBER issue, Corrected erroneous space, Added PoE to NOC Infra Ports

- switch-configuration/config/switchtypes
> Replaced confIDF with Spare

- switch-configuration/config/switchtypes
> Renamed 2 switches for Expo

- README.md
- docs/checklists/PRECONF-CHECKLIST.md
- pi/README.md
Initial checklist to capture things that have been done preexpo
Adding note about the rpi build instructions
> [READY] - Initial checklist for preconf stuff

- switch-configuration/config/types/Booth
SODA Machine VLAN Implementation
No SODA for you
SODA distributor enabled
SODA poured on Keyboard
> added port for SODA machine

- switch-configuration/config/switchtypes
Stop monitoring unused switches
Stuff got hung up on irrelevant crap
No more hangups
Thomas Dolby shocked the monkey.
> Od 21x patch02 Cleanup on aisle 5 (switch types)

- switch-configuration/config/scripts/switch_pinger
Loops and Loops and Loops and...
Run and exit
-d <n> will delay for n seconds and loop
Let's just say it involved lots of lubricant, surgical tubing, and a yak.
> Added -d <n> option to switch_pinger

- switch-configuration/config/types/Catwalk
- switch-configuration/config/types/exIDF
Uncorking the network
exVmVendor not trunked
exVmVendor might actually work
Have to push to switches to test.
> Added SODA machine to trunks

- switch-configuration/config/types/Catwalk
Ooops
Misspelled
Correct spelling
Fed yak to leather goddesses.
> [URGENT][READY] Fixed typo

- nix/machines/_common/users.nix
> [READY] add dlang ssh key

- nix/machines/_common/users.nix
Add Rueben to users list w/ pub key
Rueben wasn't here!
There's now a Rueben user.
right....
> [READY] add a user for rueben w/ pub key

- nix/tests/flake-module.nix
Fix buildInputs
`nix flake check`
> [READY] - fixing test

- switch-configuration/config/types/Booth
More SODA fixes
SODA didn't work
SODA works
You put your dollar in, you pull your config strip out.
You put your distro in and you shake it all about.
You do the SODA dance and you NUCC yourself around.
That's what it's all about!
> [READY] SODA is hard

- switch-configuration/config/scripts/switch_template.pm
Multiple Fixes
Borked
Less Borked
We took it into the cave and a hollow voice said "Plugh"
> Fixes for DHCP and ICMP6 problems on Expo

- nix/machines/_common/users.nix
Add Ryan to nix users
Ryan not in nix users
Ryan in nix users
this was already pre-applied and then got wiped with a master deployment, we're confident it works.
> [READY] Add Ryan to Nix admins

- router-configuration/backups/br-mdf-01
- router-configuration/backups/cf-mdf-01
- router-configuration/backups/ex-mdf-01
Saved configs at end of 21x
Stored configs were 3+ years old
Current config backups
Vincent Kapoor:
You want to send him into space under a tarp?
Bruce Ng:
Yes. Can I go on?
Vincent Kapoor:
NO!
> Updated router config backups

- nix/machines/_common/users.nix
- nix/machines/devServer/default.nix
- nix/machines/devServer/hardware-configuration.nix
- nix/machines/devServer/libvirt.nix
Add libvirtd to devServer with Kyle's keys
- devServer was not a hypervisor
- Kyle's key old
- devServer should be running libvirtd
- Kyle's keys updated to new ones
will apply to devServer with @sarcasticadmin
> Add libvirtd to devServer and update Kyle's keys

- nix/machines/_common/users.nix
Adding myself to users for nix
Josh was not a user and key was not tracked
Josh user `jsh` is added and key is included for access
na
> [READY] - Adding Josh to users

- .github/workflows/ci.yml
Only 1 package and 0 nixos configurations where being built in CI. Now they all are.
> [READY] ci: add package and nixos config builds

- switch-configuration/README.md
- switch-configuration/config/miniconfig
Updated ssh keys for miniconfig
Loaded miniconfig on Juniper switch
> Updated ssh keys for miniconfig

- facts/keys/carlyn_id_ed25519.pub
Adding key for carlyn's laptop
did not authenticate carlyn's laptop
should authenticate carlyn's laptop
was not tested
> adding Carlyn's key

- switch-configuration/config/miniconfig
added Carlyn's public key to miniconfig
did not have Carlyn's public key in miniconfig
miniconfig authenticates Carlyn
this was not tested
> miniconfig authentication for carlyn

- facts/keys/danny_id_ed25519.pub
Adding Danny Keys
not being authenticated
will be authenticated
> Adding danny keys

- switch-configuration/config/scripts/Loader.pm
Instrumented Loader.pm
Loader.pm was less informative
Loader.pm tells you more about what's happening in its early stages
1. Wet finger.
2. Hold finger in wind
3. First side of finger to dry indicates direction from which wind is blowing
> [READY] - Instrumented Loader.pm use of Ping and Interfaces calls

- switch-configuration/config/trunktypes
Unfucked the switch types file
Generated bogus configurations for trunks in conference center
Generates correct VLAN maps on conference trunks
Broke the NOC
Fixed the NOc
Yak is happy now.
We need to buy more lubricant and surgical tubing.
> URGENT: Fix errors in switch types file

- nix/nixos-configurations/core-master/configuration.nix
- nix/nixos-configurations/core-slave/configuration.nix
- nix/nixos-modules/users/conjones.nix
- nix/nixos-modules/users/default.nix
Adds nix user conjones
user account conjones exists
> [READY] nixosModules.users.conjones: adds user conjones

- facts/inventory.py
- nix/checks/default.nix
- nix/checks/wasgeht.nix
- nix/nixos-configurations/core-master/configuration.nix
- nix/nixos-modules/services/default.nix
- nix/nixos-modules/services/wasgeht.nix
- nix/packages/wasgeht/package.nix
- Adds wasgeht package overlay
- Adds wasgeht NixOS module service
- Enables wasgeht service on `coreMaster`
- Adds a check for the wasgeht module
No wasgeht
Has wasgeht
`nix flake check`
> [READY] Add wasgeht

- openwrt/docs/AR71XX.md
Updated the ar71xx (ath79) instructions and account for some of the new tools (`make-dhcpd`)
> ar71xx: improve flashing instructions

- switch-configuration/config/switchtypes
Fix VLAN and IP address for 2 switches moved from EX to CF
103
503
You put your right yak in,
You put your right yak out,
You give your yak some lube,
and you shake the tube about,
That's what it's all about!
> Od 22x patch04

- openwrt/scripts/massflash/massflash
Pin Kex Algorithm and toggle amber 1gig link light when flashing completes.
- no identication
- kex algorithm experimental
- kex algorithm works since its a known good one
- 1gig link light after flash completes
- Tested on massflash
> openwrt.scripts.massflash: openwrt one

- nix/nixos-modules/users/default.nix
- nix/nixos-modules/users/gene.nix
> Add ssh keys for Gene Liverman

- nix/nixos-modules/users/gene.nix
remove extra s on attribute name to fix syntax
> Fix attribute name

- nix/nixos-modules/users/gene.nix
I used copy/paste this time... hopefully no more errors
> Fix Gene's user def... again :(

- nix/checks/wasgeht.nix
- nix/packages/wasgeht/package.nix
Updates wasgeht to 0.2.0
- wasgeht 0.1.2
- wasgeht 0.2.0
- wasgeht checks test `/metrics` endpoint
```
nix build --rebuild .#checks.x86_64-linux.wasgeht
```
> wasgeht 0.2.0

- flake.lock
- nix/nixos-configurations/core-master/default.nix
- nix/nixos-configurations/core-slave/default.nix
Follow up to #880 
- applied to coremaster and coreslave
> bump inputs for nixos-unstable

- switch-configuration/config/scripts/switch_template.pm
- switch-configuration/config/switchtypes
rename switches and minor cleanup
testing:
changes are live in the wild
> Od 22x patch07

- nix/checks/default.nix
- nix/checks/signs.nix
- nix/nixos-modules/services/monitoring.nix
- nix/nixos-modules/services/signs.nix
update signs for latest build for 22x
- scale21x image deployed
- scale 22x image deployed
- http://signs.scale.lan/ is live
- monitoring is up as well on vhost
> nixosModules.service.signs: update signs

- switch-configuration/config/scripts/switch_template.pm
The physical network in the convention center sucks, so we're making our network suck more in order to not suck even more as everything crashes and burns
APs used to enforce rate limits by nature of their antiquated and limited capabilities.
This prevented us from completely overrunning the PCC network capabilities
The new APs removed the previous bottlenecks and allowed wifi clients to uttery and completely overrun the network infrastructure.
This patch will allow us to deploy QoS to all non-IDF switches putting rate limits on the most trafficked VLANs and prioritizing AV and Infra traffic.
The patch will allow us to convert all of our show attendees into guinnea pigs. It will be fun and exciting and nothing can possibly go wrong.
> Add QoS to destroy the network in lieu of having enough bandwidth

- switch-configuration/config/scripts/switch_template.pm
Oops
Broken switches
Traffic classes defined, switches happier
I'll let you know how it goes after we deploy this.
> OOPS! Added QoS Class identifiers

- switch-configuration/config/switchtypes
> Fixe hierarchy values

- nix/nixos-modules/users/rhamel.nix
Add Ryan's new SSH key to NixOS infra.
Ryan's new SSH key did not exist on NixOS infra.
Ryan's new SSH key will exist on NixOS infra.
> Add Ryan's SSH Key to NixOS Infra

- switch-configuration/config/switchtypes
> switches: More swizzle fallout

- facts/inventory.py
> [READY] add mrtg inventory

- nix/nixos-configurations/core-master/configuration.nix
- nix/nixos-modules/default.nix
- nix/nixos-modules/services/default.nix
- nix/nixos-modules/services/mrtg.nix
mrtg-generator service for mrtg
- nixos checks core passes
- coreMaster builds as expected
> nixosModules.services.mrtg: init mrtg-generator

- switch-configuration/config/scripts/switch_template.pm
Increase AV bandwidth cap to 10g
Lower wifi cap to 10m
First instance of someone wanting to have 2 keys of the same type
Also some QoS parameter changes
Ryan's key file broke the script
Ryan changed his approach and script will now handle multiline key files.
Ran script against new key file.
> [READY] Patch to cope with Ryan being a snowflake about keys

- switch-configuration/config/scripts/switch_template.pm
QoS -- How to change screwing people over when the network is full from random to deterministic.
Now we're playing with the deterministic values for fun and profit.
(well, maybe just fun.)
> More stupid QoS swizzle

- switch-configuration/config/scripts/switch_template.pm
> Oops -- Fixed missing semicolon.

- switch-configuration/config/scripts/switch_template.pm
Even more embarrassing than 944
> Oops again -- Add missing curly brace

- switch-configuration/config/scripts/make_lldp_map
assumes
br-mdf-01 is our master router
everything of ours connected to the master router is named *01 all raspberry pi's identify themselves as pi*
all APs have names ending in -?? or -?
> re-write lldp walker diagram maker script

- nix/nixos-modules/services/monitoring.nix
- nix/nixos-modules/services/snmp.yml
mib data for snmp into grafana
- `coremaster` works
> [READY] mib data

- nix/checks/core.nix
- nix/nixos-configurations/core-master/configuration.nix
- nix/nixos-modules/users/default.nix
- nix/nixos-modules/users/samuel.nix
> [READY] Add samuel as a user :shipit:

- .kermit/README.md
- docs/checklists/PRECONF-CHECKLIST.md
- flake.lock
- flake.nix
- nix/nixos-configurations/massflash/configuration.nix
- nix/nixos-modules/base.nix
- openwrt/docs/AUTOFLASH.md
- openwrt/docs/MT7622.md
- switch-configuration/README.md
Bumping inputs for latest nixos-unstable and moving from 24.05 -> 25.05
- inputs were from march 2025 for unstable and 24.05
- inputs at latest versions of unstable and 25.05
- verified on dev-server after `nixos-rebuild`
> [READY] nix - bumping inputs
