socallinuxexpo/scale-network

.gitignore
openwrt/Makefile
openwrt/README.md

Heres some initial work for standardizing the builds for openwrt/lede so more of the team can build the images themselves for improving and testing. I'm not the best with `make` but these have been very helpful for me with my testing currently. There using the latest stable branch of `lede`.
~~I am still testing each build of the APs but I wanted to get everyones thoughts on what I have so far. I'll probably have some fixups before this is ready to be merged.~~ All three models took the builds correctly for the most recent version of LEDE: `17.01.4`
@owendelong @irabinovitch @hriday @jaymzh @kylerisse

Makefile for openwrt/lede builds for 3700, 3800, and 3800ch

---

openwrt/flash

set the machine to an address that can talk to 192.168.1.1
hook up a powered off netgear wndr3800, run the script
hold down the reset button and power on the AP, when it prompts for a name, enter the name and the script will flash the AP and save the name and mac address to a csv file, and then loop back for the next device

script to flash netgear APs

---

facts/secrets/openwrt.yaml.example
openwrt/diffconfig
openwrt/files/etc/rsyslog.conf
openwrt/files/etc/zabbix_agentd.conf

Simple `zabbix`  and `rsyslog` remote config. Fulfills #34
Adding and removing a few packages
```diff
- odhcpd
+ jq
```
Zabbix was installed but not configured. Rsyslog was only logging locally
* Zabbix now can be templated out and included in the image
* Rsyslog now sends logs to a remote host
Yes zabbix did log to my test rsyslog server
None for zabbix, I dont have the server to test with yet. Based this config off 2016 and 2017 configs

[READY] Simple zabbix & rsyslog configs

---

facts/secrets/openwrt.yaml.example
openwrt/Makefile
openwrt/diffconfig
openwrt/files/etc/apinger.conf
openwrt/files/etc/config/wireless
openwrt/files/etc/crontabs/root
openwrt/files/etc/logrotate.conf
openwrt/files/etc/logrotate.d/rsyslog
openwrt/files/etc/rc.local
openwrt/files/etc/resolv.conf
openwrt/files/root/bin/wifi-details.sh

This allows us to monitor gateway endpoints and turn off wifi networks when the gateways are not reachable. Fulfills #15 
Wifi radios were always advertising the wireless networks even if the network was unhealthy
* Wifi networks are taken down when the endpoint is not reachable
* Added @davidelang's wifi report script
* Added logrotate package and config
* Added rrdtool1 package
* Resolver is now configurable
* Fixed some `Makefile` issues
Tested on `3700v2` and this will be the image used for testing on sunday

[READY] wifi gateway monitor and then some

---

switch-configuration/config/scripts/build_switch_configs.pl
switch-configuration/config/vlans.d/Bridged

Create output directory automatically
Did not create output directory
Creates output directory if needed, properly errors if not possible
Run script Run. -- Forest Gump

Fixed #58, syntax vlans.d/Briged (spaces->tabs)

---

ansible/inventory.py
facts/aps/aplist.tsv

Adds APs as hostgroup to Ansible automation. This serves as a building block for future work related to APs such as DNS, channel setting scripts, etc.
APs were not accounted for
APs are now a hostgroup
Imported the latest copy of aps.room.list from server5, removed redundant mac-address column, and ran the following command to issue a ping. (Please not the use of raw module since OpenWRT does not have python):
`ansible -u root -i inventory.py aps -m raw -a "ping -c 1 8.8.8.8"`

[READY] Adds AP inventory to Ansible

---

facts/secrets/openwrt.yaml.example
openwrt/Makefile
openwrt/README.md
openwrt/files/etc/config/network

Fulfills #117 
Its time to get rolling on the `openwrt` front for Scale 17x!
Existing `openwrt` build was referencing old SHA from Scale 16x. I needed to investigate to make sure that the build process still works on our existing hardware against latest `master`. I know that the goal is to get the process working with the newer model but this is an initial step in that direction.
Ideally I'm hoping this build process supports both models of APs (well see how feasible that is).
@owendelong @davidelang @kylerisse
* Building against old SHA from scale16x
* Old link in README.md
* Hardcoded mgmt interface during crunchtime: #78 
* Latest images were build and successfully running our code as intended!
* Updated documentation
* Refactored `go templating` to remove hardcode mgmt interface and …

[READY] Updating build to latest openwrt master

---

MAPS.md
README.md

@sbibayoff I added these to `s3` instead of directly in git. That way theres no having to mess with `git-lfs`. This was my alternative to #124. Let me know what you think.
Sorry for the delay.
We didnt have maps
Now we have maps for the Pasadena Convention Center from 16x 
Links work

[READY] Adding links to maps pdfs

---

ansible/inventory.py

During further investigation for #144 found an error with DHCP services due to changes in the Expo vlans.d file. This fix eliminates the cause by testing if the vlan ID is a digit. Another solution would be to comment out the offending line in that file but this PR can proceed regardless of that choice.
isc-dhcp-server would fail on start due to an invald entry in `/etc/dhcp/dhcpd.conf.subnets` related to the ex_v_ line in `vlans.d/Expo`
- Inserted a quick check when parsing the vlans.d files to test whether the vlan ID is a digit. There isn't a valid case where a real VLAN would be a non digit (in the case ofo ex_v_ containing a "-") so there's no harm in adding it.
- Reduced the number of characters in line 77 to pass pylint, unrelated to bug fix.
1. Ran `inventory.py` and verified the …

[READY] Fix DHCP issue caused by Expo file changes

---

.circleci/config.yml

Perl linting and testing
Add `-M'warnings FATAL=>q(all)'` in the perl compile and warning test to make sure that any warnings actually are treated as errors (non-zero return). Also leveraged `xargs` to make sure that we dont swallow the error like `find -exec`
Didnt exist
Adding linting and running the actual script to make sure it works
How was this PR tested? CircleCI

[READY] Perl linting and perl ci

---

ansible/README.md
ansible/etc/ansible/roles/signs/defaults/main.yml
ansible/etc/ansible/roles/signs/handlers/main.yml
ansible/etc/ansible/roles/signs/tasks/main.yml
ansible/etc/ansible/roles/signs/templates/scale-signs.service.j2
ansible/etc/ansible/scale.yml

Add an Ansible role for the signs server
No role for signs server, deployment and updates were accomplished manually
Ansible automatically deploys the signs server directly from github as a docker container wrapped in systemd. Will make on-site support a little easier despite a bit of manual effort to manage secrets initially. Changes to remote master for the scale-signs repo are easily deployed through this role.
1. Provision vagrant environment with `vagrant up`
2. Verify signs page is available by browsing to `http://10.128.3.7`
3. Use `vagrant ssh server8` to log into signs server to complete following tests
4. Verify service starts and stops using systemd `sudo systemctl restart scale-signs`
5. Generate traffic in web browser and verify logging `cd /usr/local/scale-signs && sudo …

[READY] Ansible signs role

---

ansible/Vagrantfile
ansible/etc/ansible/roles/dnsserver/templates/db.scale.lan.records.servers.j2
facts/servers/serverlist.tsv
openwrt/flash

Quick PR to cover the server names for this year, slightly update openwrt script for DL, and resolve DNS issue when a box is named monitor
Last year's server names, openwrt script didn't pause after $ap,$mac, monitor was an alias to a box name.
This year's server names, openwrt script now pauses per DL request, monitor is now a server name and not a CNAME
Doin it live!

Showtime DNS, server names

---

MAPS.md

We were missing the diagram for 17x expohall, fulfills #179 
No expohall diagram
Now have the expohall diagram link added to `MAPS.md`
How was this PR tested? NA

[READY] Adding expohall diagram link for 17x

---

switch-configuration/config/scripts/build_switch_configs.pl
switch-configuration/config/scripts/switch_template.pl
switch-configuration/config/switchtypes
switch-configuration/config/types/Catwalk
switch-configuration/config/vlans.d/Expo

build_switch_configs.pl
Improve list building logic     #186
switch_template.pl
Add consistency check for MgtVL and IPv6Addr #184
Add OSPF configuration for Expo Switches #165
Extract Vendor VLAN name prefix from configuration file #150
Improved logic for get_switchtypes #186
switchtypes
Correct Management VLAN on ConfIDF switch #184
types/Catwalk
Add vendor_backbone to ports ge-0/0/[1-3] #164
vlans.d/Expo
Formatting improvements 
Correct vendor_vlan name prefix (was ex_v_ now vendor_vlan_) #150

Issues #150, #164, #165, #184, #186

---

switch-configuration/config/scripts/switch_template.pl
switch-configuration/config/switchtypes

Added v6 router-advertisements for vendor prefixes
Improved internal documentation
Fixed IPv4 Default gateway variable name typos (defagw->defgw)
Cleaned up some erroneous indentation
IPV4 default gateway didn't make it into configuration (not fatal due to OSPF)
No IPv6 RAs for vendor VLANs
Default gateway is configured (static)
IPv6 RAs are configured for vendor VLANs
Testing -- Novel concept.

Issue #216 plus some cleanup

---

.circleci/config.yml
openwrt/Dockerfile
openwrt/Makefile
openwrt/README.md
openwrt/include/docker.mk

Fixes: #253 
Adding a openwrt build environment via docker container and circleci weekly build process
* No consistent build environment
* openwrt build container
* circle ci weekly image build process
Example of `make docker-build`:
```
$ make docker-build
docker build -t "sarcasticadmin/openwrt-build:fe4f471" .
Sending build context to Docker daemon  144.9MB
Step 1/7 : FROM hairyhenderson/gomplate:v3.2.0-slim AS gomplate
---> 16ac0ad06c9a
Step 2/7 : FROM ubuntu:16.04 as build
---> 7e87e2b3bf7a
Step 3/7 : RUN apt-get update &&    apt-get install -y sudo time git-core subversion build-essential gcc-multilib                        libncurses5-dev zlib1g-dev gawk flex gettext wget unzip                        curl python &&    apt-get clean
---> Using cache
---> f47b7beb930a
Step 4/7 : COPY …
```

[READY]: Initial openwrt build docker container and weekly builds

---

facts/secrets/ar71xx-openwrt-example.yaml
facts/secrets/ipq806x-openwrt-example.yaml
facts/secrets/openwrt-example.yaml
openwrt/README.md
openwrt/files/etc/config/system
openwrt/include/tests.mk
tests/serverspec/spec/openwrt_show/init_spec.rb
tests/unit/openwrt/golden/ar71xx/etc/config/system
tests/unit/openwrt/golden/ipq806x/etc/config/system

Fixes: #182 
This allows us to be able to have a visual cue about whether or not the image was flashed correctly. 
* WPS LED was always off
* For even scale conferences the WPS led will be `on` and for odd scale conferences it'll be `off`
* Moved ntp config to `facts`
* Added tests for ntp config serverspec
* Flashed and validated that WPS LEDs are ON as expected on both ipq806x and ar71xx builds
* Also tested the inverse for odd scale numbers where WPS LED is OFF

[READY] issue-182 - Adding WPS LED build identifier

---

openwrt/Makefile
tests/serverspec/spec/shared/openwrt/init.rb

Fixes #251 
~~Adding build identifiers for both template generation and the actual build generation since they could vary if template info isnt necessarily updated but the openwrt build is.~~
~~@kylerisse would you mind checking this out? What are your thoughts on the naming for the `*.info` files? Do you think we should make it more obvious that this is a `SCaLE` file? I know you had some suggestions when we last talked about it but I couldnt remember the details, open to any suggestions here.~~
FYI, Im including the following in the `/etc/scale-release`:
```
- git SHA from this repo
- git SHA of openwrt
```
I opted to contain the build info into a single file: `/etc/scale-release` to align with the existing `/etc/openwrt-release` file which is included with the openwrt project. The …

[READY]: Adding build identifiers to openwrt

---

.gitignore
router-configuration/backups/br-mdf-01
router-configuration/backups/cf-mdf-01
router-configuration/backups/ex-mdf-01
switch-configuration/config/scripts/build_switch_configs.pl
switch-configuration/config/scripts/switch_pinger
switch-configuration/config/scripts/switch_template.pl
switch-configuration/config/scripts/update_switches
switch-configuration/config/types/Booth
switch-configuration/config/types/Catwalk
switch-configuration/config/types/cfAV
switch-configuration/config/types/cfIDF
switch-configuration/config/types/cfRoom
switch-configuration/config/types/exIDF
switch-configuration/config/types/exRoom
switch-configuration/config/types/registration
switch-configuration/todo

Fixes: #266 
Adds the ability to auto-generate printed switch maps (PostScript files) from configuration
Also includes backups of the router configuration files and some checkpointing of new scripts that aren't yet in use.
This feature did not exist
This feature works
Manual review of a complete set of generated PS files

[READY] auto-generate printed switch maps and router backups

---

.circleci/config.yml
facts/datasource.py
facts/test_datasources.py

Fixes #274 
- Adds CSV validation to Circle as a bare minimum to tackle #274 . Tests are executed in a generic pytest wrapper that I created which can be easily extended for new data sources, while leveraging the same validation functions across files. No need to change regexes everywhere or write a ton of code. The goal was to make adding new files as simple as created a standardized dictionary along with 2 lines of boilerplate code. 
- ansible_test ci phase is now dependent on the data validation. If data is bad, no need to continue testing inventory.
- This PR does not tackle any of the TSV files used by Ansible or Switch configuration, only CSV for now. I'd like to see if the team likes the approach to testing data files before moving on to that portion. I may have stretched the …

[READY] CSV validation

---

.circleci/config.yml

Fixes: #119 
This was fallout from #263 since I  forgot to update the path for the build artifacts from circle, this resulted in a failed build from saturday nights weekly build.
* Failed build: https://circleci.com/gh/socallinuxexpo/scale-network/899
* Build needs to have ath79 path instead of the old `ar17xx` path
* At the moment it needs to be merged until the next weekly build takes place. But path confirmed to work on building locally.

[READY] issue-119 - Support new build target type for circle path

---

ansible/roles/dhcpserver/templates/dhcpd.conf.subnets.j2
ansible/roles/dhcpserver/templates/dhcpd6.conf.subnets.j2

Since we are running only a partial network for the workparty (at least at this point) I ran into a case where a jinja template was always assuming two dns servers. I believe this fixes it but needs more testing
* Assumes two dns servers for dhcp config
* Handles cases for both single and multiple dns servers
* Only tested the single case
* TBD on multiple once we get to scale18x

[WIP] Correctly handle case for single dns server

---

switch-configuration/config/scripts/switch_pinger

swith_pinger now detects if it's on OSX and removes -W 1 from the ping command
Tested on osx and using an ubuntu vm

[READY] removes -W 1 from ping on osx

---

switch-configuration/config/scripts/override_switches
switch-configuration/config/switchtypes

Adds -l flag to override_switches
Could only send config to DNS name of switch
Allows sending config via Management Port on the back of the switch
Configured 6 switches using this method.

Od.18.p8 -  flag to override_switches

---

openwrt/scripts/local/ap_command.sh

this is so that you can capture the stdout to use for other things
without having the up/down/summary data captured in your output
move housekeeping info from stdout to stderr so you can redirect stdout to capture the scripted output without capturing the housekeeping 
housekkeping messages go to stdout and are mixed with the ap command output 
couldn't ping messages and final summary data goes to stderr instead of stdout
in prod

redirect housekeeping info to stderr

---

.github/workflows/trigger.yml
.gitlab-ci.yml
facts/secrets/ar71xx-openwrt-example.yaml
openwrt/Makefile
openwrt/autoflash
openwrt/scripts/local/dhcpd_net.sh
openwrt/scripts/local/gather-artifact.sh
tests/serverspec/spec/spec_helper.rb
tests/unit/openwrt/golden/ar71xx/etc/config/network.0
tests/unit/openwrt/golden/ar71xx/etc/rsyslog.conf
tests/unit/openwrt/golden/ar71xx/etc/zabbix_agentd.conf

Putting up some of the work that was done during 18x around `autoflashing` the wndr3800ch.
There are a lot of things going on in the MR so Ill try to cover all of the methods to my madness:
* Had to do flashing manually
* Configs for wndr builds didnt reflect conference configs
1. First and foremost we have successfully integrated automated flash of the WNDR 3800ch that we modified during Scale 18x. It is being done via a gitlab-ci runner running on a raspberry pi 2 that we had laying around. Thats controlling a relay to toggle the power and the GPIO pins to "press" the reset button. This is all coordinated via `openwrt/autoflash` script being called via the gitlab ci pipeline.
2. The `gitlab-ci` pipeline is broken down into two components: `openwrt-ar71xx-build` and …

[READY] Autoflash on actual WNDR hardware

---

MAPS.md

Originated from @irabinovitch via https://github.com/socallinuxexpo/scale-network/pull/363 but would prefer to keep these binaries out of the code repo and have them hosted in s3 until #286 is dealt with.
At the time of adding these files to s3 there sha256sums are as follows:
```
bf4566e553a14e35dc6fcb3b876dbd898fc44e183c3039c0c9486a9d14df43f4 Zpasadena-cc-exp_GES.dwg
fd6f85989ce7a87d6f0027feff672218052b2b4f859c7ec62463edf9f11b21bc Zpasadena-cc_GES.dwg
```
Excluding the following from the original PR https://github.com/socallinuxexpo/scale-network/pull/363 since it was a duplicate:
```
fd6f85989ce7a87d6f0027feff672218052b2b4f859c7ec62463edf9f11b21bc pasadena-cc-lower-and-upper-level_GES.dwg
```
- Missing these CAD files
- CAD drawings pushed to s3
- Links to CADS add to `MAPS.md`
All …

[READY] - Adding ref to dwg PCC CAD diagrams from Ilan

---

README.md
RELEASE.md

Fixes: #376 
Our existing release process wasnt documented. Figure it was time to document this so its more visible across the team 🙂 
- Release docs were missing
- Release process as-is is now documented
- Markdown renders and links work

[READY] - Adding releasing docs for existing process

---

.github/workflows/openwrt-build.yml

Part of: #377 
As an alternative to our existing circleci builds we current have:
https://github.com/socallinuxexpo/scale-network/blob/a745d0437f1f02da9f290354dda09ab8370eae6b/.circleci/config.yml#L29-L76
There seems to be a good amount of usefulness to doing this in github actions:
1. We get to trigger the builds via `workflow_dispatch` (https://github.blog/changelog/2020-07-06-github-actions-manual-triggers-with-workflow_dispatch/) for any given branch in addition to doing periodic `cron` builds weekly like we current have in circleci. Anyone write access to the repo can now trigger this `workflow_dispatch`. **Example:** if a team member makes a change in a PR, they can trigger this workflow (a build) and then make artifacts for testing. Previously you would have had to do that build …

[READY] - Building openwrt imgs using github actions

---

switch-configuration/Makefile
switch-configuration/config/scripts/generate_ps_refs.pl

Fixes: #390 
Generating pdfs as output for the switches. This is @owendelong work from our sync up in SD. Thanks @owendelong!
- No output for pdfs for the cable team
- PS artifacts for cable team to generate .pdf
- Start of the `makefile`
-  Build the output .ps for pdf
```
$ make switch-maps-bundle
cd config && \
perl scripts/generate_ps_refs.pl > switch-maps/bundle.ps
$ make switch-maps-bundle
make: Nothing to be done for 'switch-maps-bundle'.
```
> Caching working

[READY] - Adding reference pages for switches

---

.github/workflows/openwrt-build.yml
.github/workflows/trigger.yml
openwrt/Makefile
openwrt/autoflash
openwrt/include/tests.mk

Forget to remove my test repo (appropriately named: `actions_sanity`) from the artifact path. As a result the new build job in actions succeeded but not artifacts were found: https://github.com/socallinuxexpo/scale-network/actions/runs/1070055388
We should not have to depend on the various CI tools approaches to package up artifacts. Adding a new make recipe to ensure that its now common for the openwrt side of things. The results of the build can now be found in openwrt/build/artifacts
The upload workflow within github actions leaves a lot to be desired. There were many initial assumptions with GITHUB_WORKSPACE, paths from test repos, etc. that were originally left here. These more or less have been vetted now and this is the best result I have found to date for `scale-network`.
I am …

[READY] - Fix artifact uploads for openwrt builds

---

.circleci/config.yml
ansible/roles/signs/tasks/main.yml
ansible/roles/techteam/tasks/main.yml
ansible/roles/techteam/tasks/users.yml
ansible/roles/zabbixagent/tasks/main.yml

Fixes #394 
Ansible 19x fixes.
- SSH keys only supported RSA/DSA
- Zabbix and Docker installs failed on fresh installs
- More robust SSH key management, supporting multiple keys per user and/or multiple format
- Anisble no longer failing
- vagrant up
- vagrant provision
- verify functionality via ssh

[READY] Ansible 19x fixes

---

.circleci/config.yml
.github/workflows/openwrt-build.yml
openwrt/Makefile
openwrt/docs/BUILD.md
tests/unit/openwrt/test.sh

Relates to: https://github.com/socallinuxexpo/scale-network/pull/379
Was running into an error on the builds of our openwrt img: https://github.com/socallinuxexpo/scale-network/actions/runs/1299717141 this is from the `make templates` call:
```
mkdir -p build
curl -L -o build/b4c0d377f6bc13c555b69659ac001a25ab22bbd4.tar.gz https://github.com/openwrt/openwrt/archive/b4c0d377f6bc13c555b69659ac001a25ab22bbd4.tar.gz
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   157  100   157    0     0    846      0 --:--:-- --:--:-- --:--:--   848
0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 5873k    0 5873k    0 …
```

[READY] - Fixes for authorized_keys centralizing for openwrt

---

.github/workflows/ansible-test.yml
.github/workflows/openwrt-build.yml
.github/workflows/openwrt-golden.yml
.github/workflows/switches.yml

Follow up to PR: #413 
Relates to Issues: #377 #373
Because of course this was going to be done in more than one PR
@kylerisse was right about the decoupling for circleCI: https://github.com/socallinuxexpo/scale-network/pull/413#issuecomment-1010200826 I will be reaching out to Ilan for assistance since I dont have the permissions to unlink this repo from circleCI
- GHA syntax was incorrect for `container` attribute.
- GHA syntax errors in various other places
- Odd failure with `jq` in ansible tests due to tty differences in CI tools
- Workflows do not necessarily trigger when their own file in `.github` changes
- Reference container attribute correctly
- Fix any GHA syntax errors now that we can test in the actual PR
- Add `.` to make inventory test pass: `jq .` (see …

[READY] - [Issue-414] - Redux for phasing out circleci

---

openwrt/autoflash
openwrt/docs/AUTOFLASH.md

Fixes: #433 
Ensure that dnsmasq in autoflasher is set correctly for min leasetime. It only supports leasetimes of >=120s
- Leasetime was 30s
- rpi setup has dhclient defaulting on all interfaces
- Leasetime is now 120s (min of dnsmasq)
- rpi dhclient only enabled on interface going to external network
- rpi dhclient was disabled
- rpi tcpdump and ping for 8 hours to ensure stability
- apply to AP hardware: https://gitlab.com/socallinuxexpo/scale-network/-/jobs/2334815375

[READY] - Updating dnsmasq leasetime to reflect min

---

facts/secrets/ar71xx-openwrt-example.yaml
facts/secrets/ipq806x-openwrt-example.yaml
facts/secrets/openwrt-example.yaml
openwrt/files/etc/apinger.tmpl
openwrt/files/etc/udhcpc.user
tests/serverspec/spec/shared/openwrt/init.rb
tests/unit/openwrt/golden/ar71xx/etc/apinger.tmpl
tests/unit/openwrt/golden/ar71xx/etc/udhcpc.user
tests/unit/openwrt/golden/ipq806x/etc/apinger.tmpl
tests/unit/openwrt/golden/ipq806x/etc/udhcpc.user

Fixes: #364 
Updating `apinger` to leverage local gateway instead of google
- Leveraged google for apinger, was simplest path at the time to get this up and working at the time
- udhcpc.user had duplicate logic in the case
- set apinger inputs via `openwrt*.yaml`
- apinger status was logging to `/tmp/apinger.status`
- Removed apinger inputs in `openwrt*.yaml`
- `/etc/apinger.conf` moved to `/etc/apinger.tmpl` so that gateway can be added during dhcp bound and renew
- Default gateway ($router) used in udhcpc.user scripts to create `/etc/apinger.conf` from `/etc/apinger.tmpl`
- serverspec test added for checking that default gateway defined in `/etc/apinger.conf`
- apinger status logging to `/var/log/apinger.status`
- Built an image with the configuration: …

[READY] - Enable dynamic apinger gateway check

---

openwrt/autoflash
openwrt/docs/AUTOFLASH.md

Fixes: #429 
Not capturing serial output as part of the autoflash made it challenging anytime the AP didnt boot successfully. This seems to be a nice way to monitor this going forward and include logs from the build in gitlab CI
- No serial log captured during AP flashing process
- Serial log captured during AP flashing process
- Documentation around requirements to enable serial log
- Gitlab CI: https://gitlab.com/socallinuxexpo/scale-network/-/jobs/2329081472
- New artifacts that are being generated as a result of `socat` being integrated into autoflash:
[serial-debug.log](https://github.com/socallinuxexpo/scale-network/files/8478264/serial-debug.log)
[serial.log](https://github.com/socallinuxexpo/scale-network/files/8478266/serial.log)

[READY] - Capture serial output for AP in CI log

---

facts/secrets/ar71xx-openwrt-example.yaml
facts/secrets/ipq806x-openwrt-example.yaml
openwrt/files/etc/ssh/sshd_config
tests/unit/openwrt/golden/ar71xx/etc/config/system
tests/unit/openwrt/golden/ar71xx/etc/ssh/sshd_config
tests/unit/openwrt/golden/ipq806x/etc/config/system
tests/unit/openwrt/golden/ipq806x/etc/ssh/sshd_config

Fixes: #388 
- PasswordAuth for openwrt sshd was always enabled
- scale version in yaml config was 18
- PasswordAuth for openwrt sshd can be toggled (default to enabled)
- scale version yaml config bumped to 19 for upcoming 19x conference in July
- Will do a build and test locally since `autoflash` automation will break when password is disabled

[READY] - Adding option to toggle openwrt sshd PasswordAuth

---

openwrt/files/etc/udhcpc.user
tests/unit/openwrt/golden/ar71xx/etc/udhcpc.user
tests/unit/openwrt/golden/ipq806x/etc/udhcpc.user

Fixes mixed-case problem with host name.
See above
Mixed case host names in config vs. lower case hostnames from KEA didn't compare equally causing erroneous reboots.
Erroneous reboots from this cause are prevented.
/bin/bash

[READY] - Update udhcpc.user

---

openwrt/flash
shell.nix

Needed to solo flash (old process) 4 APs that didnt take with the massflash. Leveraging the nix-shell as well since the ping util in ubuntu still seem to be broken and doesnt show malformed ping packets :/ see: https://github.com/socallinuxexpo/scale-network/issues/295
- flash util was only workable from the rpi
- no net tools in nix-shell
- flash util leverages path for vars
- net tools in nix-shell
- Flashed the 4 remaining APs

[READY] - init flash utils and nix-shell pkgs updates

---

graphics/19x T-Shirt Front.svg

Design for T-Shirt Front for SCaLE 19x
Does not contain digitizing for Embroidery.
Add T-Shirt Front design.
We did not have a design file for the front of our T-Shirts.
We now have a design for the front of our T-Shirts.
Extensive analysis of signals in the 380 to 700 nanometer wavelengths emitted from a collection of LEDs and filtered through a matrix of liquid crystal elements triggered according to render the included file using one each mark one oculus dexter and oculus sinister.

[Ready] Create 19x T-Shirt Front.svg

---

openwrt/README.md
openwrt/docs/MASSFLASH.md
openwrt/scripts/massflash/kea.tmpl
openwrt/scripts/massflash/massflash

Fixes: #385
At the past scale work party we were able to `massflash` the entire set of 100+ APs in about 2 hours. The result of the teams efforts is the following script and configuration that made this possible
- Used to have to update each AP via the existing flash (soloflash) script
- `massflash` process exists
- `kea.tmpl` for setting up a `massflash` dhcpd server
- Flashed 100+ aps at the last workparty for scale 19x

[READY] - init massflash for APs via kea dhcpd

---

switch-configuration/config/scripts/bulk_local_load_switches
switch-configuration/config/scripts/override_switches
switch-configuration/config/scripts/switch_template.pl
switch-configuration/config/switchtypes

This PR includes changes necessary to support bulk loading configuration into switches:
bulk_local_load_switches -- New script for quickly loading configs onto switches 
override_switches -- Correct typo in comment and clarify comment.
switch_template -- Add functionality for additional fields in switchtypes, new function get_switch_by_mac
switchtypes -- Add standins for MAC addresses until real addresses can be captured. Intended to facilitate testing.
Functionality did not exist
bulk_local_load_switches will wait for the management ethernet of a switch to become available and then identify the switch by MAC address in the switch types file and load the appropriate configuration file onto the switch and commit it.
Unable to test due to resource constraints (switches in storage in …

[READY] - Owen 19x pre.04 -- Preparation for bulk loading configuration into switches

---

.github/workflows/switches.yml
facts/datasource.py
facts/test_datasources.py
switch-configuration/config/types/hiCTF

Changed build targets to accommodate Makefile edits.
Change Test targets so that Makefile can be updated.
Update tests to include support for additional fields in switch types.
Tests required target names that will be rendered obsolete.
Tests use new target names.
No testing was necessary. Literally a simple change (adding a . to the beginning) to two test target names.

Improvements to validation tests

---

ansible/roles/dhcpserver/templates/dhcpd.conf.subnets.j2
ansible/roles/dhcpserver/templates/dhcpd6.conf.subnets.j2
ansible/roles/dnsserver/files/named.conf.options
ansible/roles/dnsserver/templates/named.conf.scale-acls.j2
facts/servers/serverlist.csv

Updates to the `core` role for ansible during 19x deployment
- Support for 2 dns servers in dhcpd
- named acl conditional led to inconsistent templating
- Bind dnssec set to `auto` (default from bind iirc)
- Support for 1 or 2 dns server in dhcpd
- named acl conditional led to inconsistent templating
- Bind DNSSEC set to `no` - disabling DNSSEC for the root recursive name servers 
- Updates to the serverlist.csv for `core1` and updates to the ipv6 prefix
- ansible-playbook -u ubuntu -i inventory.py core.yml
> `core.yml` is a temp file to only test the single role

[READY] - Updates to the core role for ansible during 19x deployment

---

switch-configuration/config/scripts/override_switches

Added -I option to override_switches to allow script to proceed, ignoring failed switches.
First failed switch aborted script
If -I option is used, switch failures will not abort the script and are reported at the end of the run.
Ran it against a mostly non-existent network. Errors were reported at the end as expected.

Added -i flag to override_switches to allow ignoring failed switches

---

facts/aps/aplist.csv

it appears that the conversion script that uses aplist throws away the first line of the file, so adding a header line

add csv header

---

ansible/roles/dnsserver/templates/named.conf.scale-acls.j2
openwrt/Makefile
openwrt/docs/MASSFLASH.md
openwrt/files/etc/rc.local
openwrt/files/etc/udhcpc.user
openwrt/files/root/bin/apinger-pop.sh
openwrt/scripts/massflash/massflash
tests/unit/openwrt/golden/ar71xx/etc/rc.local
tests/unit/openwrt/golden/ar71xx/etc/udhcpc.user
tests/unit/openwrt/golden/ar71xx/root/bin/apinger-pop.sh
tests/unit/openwrt/golden/ipq806x/etc/rc.local
tests/unit/openwrt/golden/ipq806x/etc/udhcpc.user
tests/unit/openwrt/golden/ipq806x/root/bin/apinger-pop.sh

apinger updates, dhcpclient reload/restart services, and massflash being used to update the APs
- `apinger` template wasnt working when no network was present
- `dhcpclient` reboots when hostname changes
- AP will yoyo if it has amnesia of its hostname
- Fixing `apinger` on boot when no network present at first
- `dhcpclient` reloads services and system when hostname changes
- AP has stable uptime stable
- `massflash` doesnt have a hardcode sha

[READY]  - fixing apinger and massflash updates

---

switch-configuration/config/switchtypes

Correct type spec for NOC switch
Invalid type name
Valid PCC type name
Tests -- We don't need no steenkin' tests.

OOPS -- Wrong type specified for NOC switch, corrected.

---

tests/serverspec/Gemfile
tests/serverspec/Gemfile.lock

`net-ssh` has now released 7.0.1 so we no longer need to pin to the github repo
`net-ssh` was using 6.x-ish via the github repo
`net-ssh` has now released 7.0.1
- TBD

Update serverspec deps

---

flake.lock
flake.nix
nix/README.md
nix/machines/loghost.nix
nix/tests/allTests.nix
nix/tests/loghost.nix
shell.nix

Fixes: #508
Adding initial flake.nix and consuming the `shell.nix` from `devShells.default` which we added back in #395 . Additionally adding a new NixOS VM for a dedicated `loghost` server along with tests to validate it works inside qemu. Still need to try out the VM in bhyve but this is a good checkpoint from me to get feedback.
- Loghost was setup on `server3`
- flake.nix and flake.lock add for consistent reference to `nixpkgs`
- Reference shell.nix from `devShells.default`
- `loghost` is its own dedicated machine
Test the `devShell.default`:
```
$ nix develop
```
Test the vm machine via the nixos test framework. These tests actually spin up a vm and run the test suite in `nix/tests/loghost.nix`:
```
~$ nix build ".#packages.x86_64-linux.scaleTests.loghost"
```
Also able to build the …

[REVIEW] - init flake.nix and loghost machine build

---

LICENSE

Relates to: #516 
After speaking with @owendelong we've decided on the following license for this codebase.
- No license was present in the repo
- License set to BSD 3-clause
- NA

[READY] - init BSD 3-clause license

---

.github/workflows/openwrt-build.yml

Fixes: #515 
- actions/upload-artifact was set to v2
- actions/upload-artifact set to v3.1.1
- Manually triggered the openwrt-build action: https://github.com/socallinuxexpo/scale-network/actions/runs/3795442315 Even though its the "old" build it still confirms what we need: The artifacts are still captured properly after the build

[READY] - Update artifact upload GHA to v3.1.1

---

flake.nix
nix/machines/loghost.nix
nix/modules/bhyve-image.nix
utilities/bhyve/templates/loghost.conf

Adding necessary bits to support running on bhyve for the images produced via nix.
- loghost was only being specific to a qemu image format
- update tests to use `callPackage`
- adding bhyve config for loghost - Proposing to put this in `utilties/bhyve` instead of `ansible/roles/bhyve`
- bhyve image nix function
- loghost support bhyve image gen
Able to build and run a nixos vm on bhyve:
```
$ nix build ".#nixosConfigurations.x86_64-linux.loghost.config.system.build.bhyveImage"
```
> Produces a bootable, compatible image when applied with the vm config
Building qemu images still works as well:
```
$ nix build ".#nixosConfigurations.x86_64-linux.loghost.config.system.build.vm"
```

[REVIEW] - init bhyve image support for nixos images

---

facts/inventory.py
nix/machines/core/default.nix
nix/tests/core.nix

Updates to kea configuration on core server.
- Had issues with mac address setting via systemd
- simplify the systemd-networkd config (going to override the mac at the bhyve level instead)
- Adding actual client/server dhcpd test for core
- define user-context per subnet for vlan name
- init subnet ids for kea
- core test wait for network on coreserver to common online
Client/server test for dhcp passes. Current test scenario is: Kea server starts with currrent configuration and is tested via builtin `-t` flag. Kea client comes up and tries to get a lease then pings the server:
```
nix build ".#packages.x86_64-linux.scaleTests.core"
```
Confirmed dhcp options are being passed as expected with APs configurations as well.

[READY] - Updates to core server and kea config

---

flake.nix
nix/machines/_common/users.nix
nix/machines/core/common.nix
nix/machines/core/master.nix
nix/machines/core/slave.nix
nix/machines/loghost.nix
nix/modules/bhyve-image.nix
nix/tests/core.nix

Support bind slave for coreconf vm
- Originally vms were only bootable via ahci device type
- no slaves for bind were supported
- split master & slave configs for core machine
- adding common to core
- support nvme devices for booting
- common config cleanup
Will test completely when hosts are deployed
Tests passing locally
```
$ nix build ".#packages.x86_64-linux.scaleTests.core"
```

[READY] - supporting bind master and slave with nvme devices 

---

facts/inventory.py
flake.nix
nix/machines/core/slave.nix
nix/machines/loghost.nix
nix/tests/core.nix

- no set in nixosConfiguration for flake
- loghost necessary pkgs
- add in missing ipv4 gateway in kea.config
- new test for route
- parameterize the core tests
- disable ipv6 privacy configs for core* roles
- move slave zone file store to `/var/run/named`
- Rebuild switch working on `coreexpo`:
```
nixos-rebuild switch --flake github:socallinuxexpo/scale-network/393c224d8ebb5ed44f05bba8e28fe1912bd6f0e0#coreMaster
```
- Verified zone transfers are working from `coreexpo`

[READY] - nixos-rebuild switch works and kea default route set

---

openwrt/docs/AR71XX.md

Corrects typo/error in `openwrt/docs/AR71xx.md`
instruction to set workstation static ip to 192.168.1.1 however the router will be using this address.
instruction to set workstation static ip to 192.168.1.5.
Looks good

[READY] Fixed ip address in openwrt/docs/AR71xx.md

---

facts/inventory.py

fixes #570 
- no cnames for loghost, monitoring, and zabbix
- cnames for loghost, monitoring, and zabbix
locally ran inventory script, here's output
```
$ cat /tmp/inventory_test/db.scale.lan.records | grep monitoring1
monitoring1  IN  AAAA    2001:470:f026:103::6
monitoring1  IN  A    10.0.3.6
loghost IN    CNAME   monitoring1.scale.lan.
monitoring IN    CNAME   monitoring1.scale.lan.
zabbix IN    CNAME   monitoring1.scale.lan.
```

[READY] add additional cname records for monitoring1

---

nix/machines/signs.nix

bumping the sign container on the nix vm
- signs display the right talks at the right time

[READY] - new sign image for dst spring forward

---

.github/workflows/openwrt-build.yml
.github/workflows/trigger.yml

Fixes: #605
Some of the GHA workflows were using a deprecated version of ubuntu and
it was causing failures. Example:
https://github.com/socallinuxexpo/scale-network/actions/runs/4648537091
- Some workflows were running on 18.04 which was deprecated
- Bumped workflows to use 22.04
- Able to trigger a workflow via this branch and it built successfully: https://github.com/socallinuxexpo/scale-network/actions/runs/4706054646

[READY] - update workflows runs-on to 22.04

---

.github/workflows/trigger.yml

Fixes: #511
Depends on: #606 
Leverage the opensource workflow: https://github.com/Nebulaworks/action-standardize-pr-comment
Allows us to be able to test the workflows while in the PR vs having to merge and then test (fail on continuous delivery).
- Could only test the trigger GHA workflow on `master`
- Can test the `trigger` GHA workflow from PR
- I believe this will need to be merged in `master` prior to being able to test this for the first time

[READY] - init pr-standardize-comment for trigger workflow

---

.github/workflows/openwrt-golden.yml

Blocks: #611 
For gomplate testing lets bump this container to match whats in the nix shell: v3.11.3
- Gomplate was using an older version which caused it to break recently: https://github.com/socallinuxexpo/scale-network/actions/runs/5791484774/job/15696369527?pr=611
- Leverage a newer version of the container thats compatible with the latest version of actions/checkout@v2
- https://github.com/socallinuxexpo/scale-network/actions/runs/5791587798

[READY] - Bump alpine container for golden tests

---

.github/workflows/trigger.yml
openwrt/include/tests.mk

Relates to: #511
Testing out the behavior for triggering our GHA action build tests in the comments so we are able to testing changes to a commenting action in an open PR.
**UPDATE**:
- Need to figure out why the gitlab integration is longer working out of the blue: https://github.com/socallinuxexpo/scale-network/actions/runs/4858019542/jobs/8659022807
> After looking into it this was due to the ref of the branch being parsed incorrectly and was resulting in the 400.
- rotated our gitlab action trigger token in testing all of this so
- leveraging a newer GHA comment action thats more current
- spun out follow up issue for deprecation warnings: https://github.com/socallinuxexpo/scale-network/issues/610
- github action triggers as expected with the standardizing action: …

[READY] - [issue-511] - Testing changes for gha comments

---

.github/workflows/trigger.yml

Fixes annoying failing comments in any issue.
- Issue comment triggers a GHA that fails
- Issue comments are skipped correctly correct in GHA (but still run due to how actions)
- PR comment still working: https://github.com/socallinuxexpo/scale-network/actions/runs/6299070552/job/17099125555
- Cannot test the issue comments until this is merged into `master`

[READY] - referencing new standardize pr comment for event url

---

.github/workflows/validate-datafiles.yml
facts/datasource.py
flake.nix

- init pytest check via flakes
- datasources.py: leverage with for opening up data files
- updating action for datafiles
- Docker was used to run pytest and pylint on datafiles
- move pytest and pylint to nix check
- https://github.com/socallinuxexpo/scale-network/actions/runs/6338478727

[READY] - Validate datafiles without docker

---

.github/workflows/trigger.yml
tests/serverspec/spec/shared/openwrt/init.rb

Fixes: https://github.com/socallinuxexpo/scale-network/issues/610
Relates to: #611 (python3 removal)
More deprecations from gha, specifically `set-output`: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
- trigger workflow uses `set-output`
- Checking for python3, and zabbix in serverspec tests
- trigger workflow uses `$GITHUB_OUTPUT`
- removed serverspec tests that were checking for binaries/services that are no longer present
- result: https://gitlab.com/socallinuxexpo/scale-network/-/jobs/5484332703 
- result: https://gitlab.com/socallinuxexpo/scale-network/-/pipelines/1064632364
- Confirmation that variables are propagating with gha output updates:
```
{"ref":"rh/1696716150gha","variables":{"OPENWRT_INTEG":"YES","WORMHOLE_CODE":"t …
```

[READY] - gha: removing set-output due to deprecation

---

facts/datasource.py

Fixes #480 
Updates data validation to be more verbose.
- field based test failures did not display the file name or specific validation failure
- column based test failures did not display the file name
- filed based test failures now display the file name and function name
- column based test failures now display the file name
Locally:
1. Fix for issue 480, this is the new output of a field based validation with file name and function name added:
```
> pytest -vv -p no:cacheprovider
================================================================================= test session starts =================================================================================
platform darwin -- Python 3.11.3, pytest-7.1.3, pluggy-1.0.0 -- /nix/store/mcfk7g2qscks090ww00kzlxzqdk0z02x-python3-3.11.3/bin …
```

[READY] add better datastore test clarity

---

nix/machines/_common/users.nix
nix/machines/bootstrap/bootstrap.sh
nix/machines/bootstrap/default.nix
nix/machines/flake-module.nix

@owendelong and I used this to get out devServer running in the fremont datacenter and the kvm hosts that we run all the vms on top of.
- owen user was missing
- no bootstrap image
- owens user has been added to the list of users temporarily. Will eventually read this in via the list in facts
- bootstrap image buildable
- Builds successfully: `nix build .#nixosConfigurations.bootstrapImage.config.system.build.isoImage`
- Copied the iso to a usb stick and booted it

[READY] - Creating a bootstrap image for bringing up physical hosts

---

switch-configuration/config/miniconfig
switch-configuration/config/scripts/switch_template.pm

Fixes: #389 
Disable password based SSH logins on switches
Switches allowed password or ssh-key based logins via SSH
Switches only accept public-key authentication over SSH
No testing required, small text change in proto config files.

[READY] Issue #389 disable password based SSH logins on switches

---

facts/datasource.py
facts/test_datasources.py
switch-configuration/config/scripts/switch_template.pm
switch-configuration/config/types/Catwalk
switch-configuration/config/vlans.d/Expo
switch-configuration/config/vlans.d/Hilton

Add configuration to support VM Vending Machine in Expo Hall
We didn't have to worry about DefCon bringing complexity to our network.
Should (hopefully) support last minute request for a vending machine to support short term VMs for people to use for mischief.
There's no way to test this in advance, we just have to cope with whatever happens as it comes up.

[Ready] Added last-minut request for Expo Hal VM Vending Machine (against my better judgment)

---

nix/machines/_common/users.nix
nix/machines/bootstrap/bootstrap.sh

Follow up from #658 and comment: https://github.com/socallinuxexpo/scale-network/pull/658#discussion_r1466948661
FAT32 will be used to provide the UEFI partitions from now on and will include labels.
- vfat UEFI partitions for hypervisors
- sudo was asking for a users non existant user password
- FAT32 formatted partitions for hypervisors
- sudo will ask for root's password, without any lecturing
- sudo changes checked out when applied again this branch on the hypervisor
- Will have to wait until the next time we use the bootstrap script to verify the formattings good

[READY] - UEFI disk formatting and sudo settings

---

nix/machines/core/common.nix
nix/pkgs/scaleInventory.nix
nix/tests/core.nix

Related to: #592
Getting ntpd enabled and running on the core machines
- ntpd was not running on the core machines
- left old ansible reference after #663 in scaleInventory pkg
- ntpd running on core and restricted to scale ipv4 and ipv6 ranges
- cleaned up old ansible ref  in scaleInventory pkg
- Running vm locally confirms that is working as expected:
```
nix build .#nixosConfigurations.coreMaster.config.system.build.vm
```
- Running the vmtest for core works as expect:
```
$ nix build -L .#checks.x86_64-linux.core
```

[READY] - enable ntpd on core machines

---

facts/inventory.py
flake.lock
flake.nix
nix/machines/_common/base.nix
nix/machines/_common/time.nix
nix/machines/core/common.nix
nix/machines/core/master.nix
nix/machines/core/microvm-config.nix
nix/machines/core/slave.nix
nix/machines/flake-module.nix
nix/machines/hypervisor/hardware-configuration.nix
nix/machines/hypervisor/hypervisor2.nix
nix/machines/loghost.nix
nix/machines/monitor.nix
nix/machines/signs.nix
nix/tests/core.nix

Relates to: #660 #593
Baseline configuration for hypervisor using: https://github.com/astro/microvm.nix
There will be more follow ups but as you can see theres already a lot here so Id like to get this reviewed where things currently sit.
- Bhyve config and hosts
- no time being included in dhcp info 
- servers were using external ntp for getting time
- microvm project as the hypervisor config (qemu)
- kea ntp configs for dhcpv4
- kea binding workaround after having issue with systemd service startup: https://gitlab.isc.org/isc-projects/kea/-/issues/2776
- New runNixOSTest for verifying that bind zone for `scale.lan` is valid
- update kea reservation config due to deprecated option: https://kea.readthedocs.io/en/kea-2.2.0/arm/dhcp4-srv.html#fine-tuning-dhcpv4-host-reservation
- simple …

[READY] - Hypervisor, kea, and ntp configs

---

facts/inventory.py
monitoring/openwrt_dashboard.json
nix/machines/monitor.nix

relates to: #567 
No dashboards configured by default for grafana
openwrt grafana dashboard
nix build
@sarcasticadmin is going to test with a local OpenWRT deployment since I dont have any hardware

[READY] [Issue-567] - Adding OpenWRT Grafana Dashboard

---

nix/dev/flake-module.nix
switch-configuration/Makefile
switch-configuration/README.md
switch-configuration/config/scripts/generate_ps_maps.pl
switch-configuration/config/scripts/generate_ps_refs.pl
switch-configuration/config/scripts/generate_ps_stickers.pl
switch-configuration/config/scripts/switch_template.pm
switch-configuration/config/types/Booth
switch-configuration/config/types/Catwalk
switch-configuration/config/types/MassFlash
switch-configuration/config/types/cfAV
switch-configuration/config/types/cfIDF
switch-configuration/config/types/cfNOC
switch-configuration/config/types/cfRoom
switch-configuration/config/types/exIDF
switch-configuration/config/types/exRoom
switch-configuration/config/types/registration

Many improvements to sticker generation process and some fixes to types files
All trunks were same color.
Trunktypes field didn't exist in types files.
Did not automatically generate PDFs from PS files.
Makefile contained obsolete targets.
Improved Makefile
Color coded different trunks by type.
Changed trunk label from TRUNK to trunk type.
Makefile now autogenerates PDFs from generated PS.
Eliminated obsolete "bundle" target for PS from Makefile.
Generated sticker and refs PDF files viewed in Apple Preview (PDF viewer)
Output loosely validated by a pair of Mark 1 eyeballs as input devices to a Mark 1 HumanBrain.
HumanBrain output: "Looks about right."

[READY] Od pre21x 05

---

.gitignore
nix/machines/massflash.nix
openwrt/docs/MASSFLASH.md

Fixes: #587
Routing table shouldnt set the default route to the massflash vlan. Prior to this we would have to run the following after the massflash laptop joined a wifi network to get out to the internet:
```
ip route del default via 192.168.252.1
```
- Explicitly setting `massflash` vlan as default route
- Omit any default route for the `massflash` vlan
- update docs for massflash since there were formatting errors
- .gitignores for some of the nixosTest vm images and history
- `nix build .#nixosConfigurations.massflash.config.system.build.isoImage` and added massflash to wifi network and it was able to reach the internet without having to remove the default route

[READY] - massflash routing table fix

---

facts/inventory.py
facts/test_inventory.py
facts/testdata/dir.d/Expo
nix/machines/_common/base.nix
nix/machines/core/common.nix
nix/tests/core.nix
nix/tests/flake-module.nix

Fixes: #596
Depends on: #670 (Will have to rebase after)
Kea DHCPv6 using all of the existing vlans from switch configurations
A lot of this was made very easy by previous work (thanks @kylerisse ): https://github.com/socallinuxexpo/scale-network/pull/252 ,inventory.py ipv6 support, and the retired isc-dhcpv6. This was all very useful as reference for this implementation.
- kea didnt have dhcpv6
- lease time was set to 4000 sec for dhcpv4
- kea dhcpv6 configuration ([dhcp6-server.conf.txt](https://github.com/socallinuxexpo/scale-network/files/14326060/dhcp6-server.conf.txt) (ignore the .txt apartly github doesnt let you upload a .conf :laughing:)
- kea dhcpv6 service enabled on `core`
- dhcpv6 specific runNixOSTest for core test
- kea dhcpv4/v6 lease time for mgmt vlan is now 5 min
- kea …

[READY] - kea dhcpv6 config and service

---

nix/machines/flake-module.nix
nix/machines/massflash.nix

Relates to: #587
Figured it would be a good idea to include the common utilities in our massflash livecd.
- Basic utils were only included in `massflash` livecd
- `massflash` has all our utilies from `base.nix`
- Built livecd and tested on lenovo laptop

[READY] - massflash includes common utils

---

switch-configuration/config/scripts/switch_pinger

`ping` binary for linux so switch_pinger and related flags work as expected.
Also on `NixOS` it seems that `ping6` needs root permissions, more to see here: https://github.com/NixOS/nixpkgs/issues/85345
- `ping6` binary for switch_pinger
- `ping` binary for switch_pinger
- Testing on my nixos laptop

[READY] - switch_pinger: leverage linux ping binary

---

facts/inventory.py
facts/servers/serverlist.csv
nix/machines/_common/ssh/vm.nix
nix/machines/core/common.nix
nix/machines/core/master.nix
nix/machines/core/microvm-config.nix
nix/machines/core/slave.nix
nix/machines/flake-module.nix
nix/machines/hypervisor/hypervisor1.nix
nix/machines/hypervisor/hypervisor2.nix
nix/machines/hypervisor/libvirt.nix
nix/machines/monitor/monitor.nix
nix/machines/signs/signs.nix
nix/modules/facts.nix
nix/modules/flake-module.nix
nix/tests/core.nix

Setting up hypervisor1, flipping coreSlave and coreMaster so that master is now in conference building
- no config for hypervisor1
- coreSlave was in conf building
- coreMaster was in expo building
- config hypervisor1
- coreSlave in expo building
- coreMaster in conf building
- explicitly set `transfer-source` for bind slave
- Testing on `hypervisor1`, `coreMaster`, and `coreSlave`
- `nix flake check` passes

[READY] - hypervisor and core bits

---

.github/workflows/ci.yml
facts/inventory.py

related to: https://github.com/socallinuxexpo/scale-network/pull/698
Currently failing off master when aps are all defined in `apuse.csv`:
```
$ nix build .#scaleInventory
path '/home/rherna/workspace/scale-network/nix' does not contain a 'flake.nix', searching up
error: builder for '/nix/store/0v2dvmnmngz4lislshijlgjbybs2sxqm-scaleInventory.drv' failed with exit code 1;
last 8 log lines:
> Traceback (most recent call last):
>   File "/nix/store/lfs3m43yvcn3hrphicc132py43zqg9x5-scaleInventory/.repo/facts/inventory.py", line 718, in <module>
>     main()
>   File "/nix/store/lfs3m43yvcn3hrphicc132py43zqg9x5-scaleInventory/.repo/facts/inventory.py", line 697, in main
>     aps = populateaps(apsfile, apusefile)
>   File "/nix/store/lfs3m43yvcn3hrphicc132py43zqg9x5-scaleInventory/.repo/facts/i …
```

[READY] - inventory fix for aps and apsuse

---

switch-configuration/config/scripts/build_switch_configs.pl
switch-configuration/config/scripts/switch_template.pm

Urgent patch to switch config generator
VLAN names generated for vendor VLANs are invalid
Prefix is now properly applied to valid VLAN names
Fire!!

[READY][URGENT] -- Fixed Vendor VLAN Name generation

---

facts/servers/serverlist.csv
nix/machines/hypervisor/hypervisor1.nix
nix/machines/hypervisor/hypervisor2.nix
nix/machines/monitor/monitor.nix

Moving monitor vm to other building
Monitoring vm was configured for conference building but un-deployable due to other issue
Monitoring vm now configured for expo building and should be deployable
doin it live

[READY] migrate monitor vm to other hypervisor and disable nginx

---

switch-configuration/config/scripts/build_switch_configs.pl
switch-configuration/config/scripts/switch_config_loader
switch-configuration/config/scripts/switch_template.pm

Packet Packet Packet --- Packet --- Packet Packet
Switch didn't like config file error
Switch will digest the config file without reflux
Also includes improvements to config loader and push to allow skipping group Z (default for push) or including it (default for build)
Gave the switch a whole bunch of malox and threw the resulting configs at it.

[READY] Fixed filter and other errors

---

.github/workflows/ci.yml
nix/tests/flake-module.nix

Created script to check for duplicates in datafiles but didn't actually reference it from Github Actions Workflow. (The NOC is too distracting sometimes)
- Github Actions not running duplicates check script
- Github Actions now running duplicates check script
This PR: 
- https://github.com/socallinuxexpo/scale-network/actions/runs/8305421089/job/22732294997
- https://github.com/socallinuxexpo/scale-network/actions/runs/8305432083/job/22732321538?pr=741

[READY] reference duplicates check from github workflow

---

facts/inventory.py

SODA VLAN (112) is running their own DHCP
DHCP was configured to run on SODA VLAN (112)
DHCP no longer configured to run on SODA VLAN (112)
- @sarcasticadmin local integration testing plus apply branch

[READY] don't do dhcp on soda vlan

---

nix/machines/core/master.nix
tests/serverspec/spec/shared/dns/resolvable.rb

Found issues with DNS lookups over the IPv6 interface only on the core master server.
- serverspec tests for recursive DNS didn't exist
- cache network config for core master had the wrong /64 defined
- serverspec tests for recursive DNS now exist
- cache network config for core master has been corrected
- serverspec locally
- this PR branch being applied to core master after closing keynote is complete.

[READY] Fix recursive lookups against IPv6 interface of core master

---

nix/machines/core/common.nix

Since we arent using tftp over v6 and theres a race condition with both the kea v4 and v6 daemons

[READY] - disable dhcpv6 for now

---

nix/machines/core/common.nix
nix/tests/core.nix

Relates to: #537 #753
Reenable the dhcpv6 server without any rpi specific tftpboot options. We will reenable the option when #753 and the rpi firmware supports it.
- disabled dhcpv6 on `core` server
- reenable dhcpv6 on `core` server
- add `driverInteractive` specific config for `nixosTest.core` to allow for `ssh` to each test vm
- reenable `driverInteractive` graphics during tests 
- `nix build .#checks.x86_64-linux.core.driverInteractive` works as expected for all vms
- `nix build .#checks.x86_64-linux.core` works

[READY] - reenable dhcpv6 kea and nixosTest core updates

---

.git-blame-ignore-revs

First four commits were incorrect because they were written before a rebase rewrote the commit hashes.

[READY] git-blame-ignore-revs: fix commits

---

nix/machines/_common/base.nix

Fixes: #694 
Added vim config to disable mouse plus plugin for nix syntax highlighting.
Also, added locale settings for 24h military time.

[READY] - added vim config to hide mouse and locale for military time

---

flake.lock
flake.nix
nix/machines/devServer/disko.nix
nix/machines/devServer/hardware-configuration.nix
nix/machines/flake-module.nix

Instead of leveraging something like https://github.com/socallinuxexpo/scale-network/blob/ef74408a99827005e7e36f5b2b5ab78784611f1e/nix/machines/bootstrap/bootstrap.sh this moves our provisioning of systems to disko.
This configuration was used to setup the devServer utilizing the 500GB disks in a mirror.
- Previous disks were utilizing the 30 GB SSDs
- Leverage 500 GB disks for devServer usage
- `devServer` is online

[READY] - devServer disko config

---

CI.md
README.md
docs/gitlab-ci.md
flake.lock
flake.nix
nix/machines/devServer/default.nix
nix/machines/devServer/gitlab.nix
nix/machines/flake-module.nix

Putting the devServer to work and adding a hosted gitlab-runner. Currently trigger on the `nix` tag.
This will allow us to run `nix flake check` (includes vm tests)
Had to bump to nixos-24.05 since we were pretty behind (~2023) for our flake input `nixpkgs`. Will probably move to unstable after getting more time to test.
- no runner on `devServer`
- gitlab-runner on `devServer`
- `nix flake check` passes for this branch to ensure out vmTests work with new nixpkgs
- Tested using https://github.com/socallinuxexpo/scale-network/pull/788 for actual ci runs

[READY] - init devServer gitlab runner

---

.gitlab-ci.yml

Requires #789
Previous #https://github.com/socallinuxexpo/scale-network/pull/770 testing improvements have had to work around limitation of GHA (no nested VM capabilities) and limited resourcing (running existing nix GHA tests on PRs exhausts rate limits).
This enables tests to run on our own dev server self-hosted runner (PR to follow).
- GHA and gitlab SaaS were to the only way to run CI jobs
- Tag specific jobs and have them run on the dev server
- https://gitlab.com/socallinuxexpo/scale-network/-/pipelines/1532846314

[READY] - gitlab-ci nix flake check on devServer

---

facts/secrets/jroot_pw

Add Juniper root passwd SHA-256 Hash, to simplify switch config builds.
The file had to be created before generating switch configs.
This will help in automatically generating switch configs, to leverage Juniper's event handling and ZTP (zero touch provisioning mechanisms), to push configs and firmware to devices.

Add Juniper root passwd SHA-256 Hash

---

nix/nixos-configurations/dev-server/default.nix

Relates to #807 
In an effort to stand up a working ipv6 network with a expo network configuration on the dev-server in the colo. We've added a 4 port LACP interface `bond0` with VLANs to simulate expo building along with the various out network configuration that was needed.
- no bond0 interface
- `bond0` interface
- Scale Expo bridged VLANs added to dev-server `bond0` interface
- IP static addresses and routes for `10.0.3.5` for the dev-server
- Static ipv4 and ipv6 routes for the `10.0.0.0/8` and `2001:470:f026::/48` networks
- Disabling all ipv6 RAs on existing interfaces without addressing
- `nixos-rebuild switch --flake github:socallinuxexpo/scale-network/rh/issue-807-dhcp#devServer --refresh` works cleanly
- pinging across `bond0` to HE gateway
- pinging across Scale network to …

[READY] - dev-server to support bond and vlans for test environment

---

.github/ISSUE_TEMPLATE.md
.github/PULL_REQUEST_TEMPLATE.md
.github/workflows/openwrt-build.yml
.github/workflows/trigger.yml

Relates to: #808
Fixes: #818 
Follow up to: #814 #815 (since both merged prematurely) and fixing some things in github actions
- existing openwrt-build github action is failing due to incorrect user id
- github actions: uplaod-artifacts@v3.x
- templates had instructions that would render if not deleted before posting 
- github removed one of our tokens named: GITHUB_* (which is now unusable due to naming requirements of env vars)
- github action for openwrt-build set back to 1001 for user id
- updating our env var for github action trigger to gitlab. Can completely confirm this functionality until merged to `master`
- github action: upload-artifacts needs to be bumped ahead of deprecation #818
- Updated our templates so the instructions dont have to be removed when filling them out, …

[READY] - openwrt build follow up and github actions

---

openwrt/files/etc/udhcpc.user
tests/unit/openwrt/golden/ath79/etc/udhcpc.user
tests/unit/openwrt/test_udhcpc.sh
tests/unit/openwrt/uci

Adds logic to enable / disable radios if the channel dhcp option is set to "off" 
radio enable/disable is not controlled via dhcp option
confirmed on a physical ap by running the script with minimal env vars set.
Assuming physical AP is at 192.168.68. create the below script at `test_udhcpc.sh`. Then follow
```
$ cat ./openwrt/files/etc/udhcpc.user | ssh root@192.168.68.1 "c
at >  udhcpc.user"
$ cat test_udchpc.user | wl-copy
$ ssh root@192.168.68.1 "sh ./test_udhcpc.sh"
PASS
```
```
#!/bin/sh
set -euxo
export opt224="off"
export opt225="OFF"
./udhcpc.user renew
if [ "$(uci get 'wireless.radio0.disabled')" != 1 ]; then
echo "radio0 should have been disabled but was not"
exit 1
fi
if [ "$(uci get 'wireless.radio1.disabled')" != 1 ]; then
echo "radio1 should have been disabled but was not" …
```

openwrt: enable/disables radios via dhcp options

---

switch-configuration/Makefile
switch-configuration/README.md
switch-configuration/config/scripts/Loader.pm
switch-configuration/config/scripts/README.md
switch-configuration/config/scripts/switch_config_loader
switch-configuration/config/scripts/switch_template.pm

This almost certainly require merge ahead of od_pre22x_10.
Multiple updates to switch flashing process
Lots of problems.
Fewer problems and a bunch of peoples keys got added too.
Mark 1 eyeball, a USB keyboard, surgical tubing and a yak.

[READY] - Multiple updates to switch flashing process

---

nix/dev-shells/default.nix
nix/packages/default.nix
nix/packages/perl-net-arp/package.nix
nix/packages/perl-net-interface/net-interface-remove-grep-af-inet.patch
nix/packages/perl-net-interface/package.nix
nix/packages/perl-net-ping/linux-isroot-capability.patch
nix/packages/perl-net-ping/package.nix

Fixes: #801
This requires all of the perl libs to be able to run `switch_config_loader` from inside the devShell.networkSub
- No perl lib deps existed in devShell.networkSub
- perl lib deps exist in devShell.networkSub
- perl lib Net::Ping patch included in scale-network overlay
- TBD

[READY] - perl packages for devShell.networkSub to run switch_config_loader

---

switch-configuration/config/scripts/switch_config_loader

Fixes regression introduced in: https://github.com/socallinuxexpo/scale-network/pull/825
Fix stupid in switch_config_loader:126 
And later in
```
$ ./scripts/switch_config_loader -l -b
Global symbol "$Loader" requires explicit package name (did you forget to declare "my $Loader"?) at ./scripts/switch_config_loader line 233.
Global symbol "$Loader" requires explicit package name (did you forget to declare "my $Loader"?) at ./scripts/switch_config_loader line 234.
Execution of ./scripts/switch_config_loader aborted due to compilation errors.
```
Owen must have suffered from a bout of python brain and wrote syntactically (and grammatically) terrible code.
PERL will digest it and do what was intended.
Testing is for people who don't write perfect code.

[READY] Fix syntax in switch_config_loader

---

.github/workflows/openwrt-build.yml
openwrt/Makefile
openwrt/files/etc/rc.local
openwrt/files/etc/udhcpc.user
tests/serverspec/spec/shared/openwrt/init.rb
tests/unit/openwrt/golden/ath79/etc/rc.local
tests/unit/openwrt/golden/ath79/etc/udhcpc.user
tests/unit/openwrt/test_udhcpc.sh

Follow up to: https://github.com/socallinuxexpo/scale-network/issues/808
Recommendations from the OpenWrt team to leverage the latest Mediatek drivers: https://github.com/openwrt/mt76/commit/e5fef138524e63314cb96ff8314048d175294e95
which landed in the following version on upstream OpenWrt: 3dfd1f69a769bd857061b4856270dfc78e30c610
Also seeing the following shopt issue with dhcpc.user after https://github.com/socallinuxexpo/scale-network/pull/823:
```
Feb 20 17:49:44 OpenWrt netifd: mgmt (2585): /lib/netifd/dhcp.script: /etc/udhcpc.user: line 5: shopt: not found
Feb 20 17:49:44 OpenWrt netifd: mgmt (2585): udhcpc: sending renew to server 192.168.44.1
Feb 20 17:49:44 OpenWrt netifd: mgmt (2585): udhcpc: lease of 192.168.44.140 obtained from 192.168.44.1, lease time 43200
Feb 20 17:49:44 …
```

[READY] - openwrt bump master -> 021420245

---

nix/checks/monitor.nix
nix/nixos-modules/services/monitoring.nix

Use `mkDefault` for enable flags for easier toggling.
Remove `grafanaDomain` option and inline `localhost`.
Enable nginx routing and fix module definition.
Add test to check routing for grafana.
We didn't enable nginx for monitoring.
We enabled nginx for monitoring.
`nix build .#checks.x86_64-linux.monitor`

nixosModules.monitoring: enable nginx and add tests

---

facts/inventory.py

Updates inventory script to generate a [wasgeht](https://github.com/kylerisse/wasgeht) config file for all network devices.
no generated SCaLE wasgeht config file
generates a SCaLE wasgeht config file
```
[nix-flakes facts] $ python inventory.py all /tmp/inv_test/
[nix-flakes facts] $ ls -l /tmp/inv_test/
total 304
-rw-r--r-- 1 kylerisse users   5612 Feb 26 20:48 db.ipv4.arpa.records
-rw-r--r-- 1 kylerisse users   8230 Feb 26 20:48 db.ipv6.arpa.records
-rw-r--r-- 1 kylerisse users  13230 Feb 26 20:48 db.scale.lan.records
-rw-r--r-- 1 kylerisse users 158261 Feb 26 20:48 dhcp4-server.conf
-rw-r--r-- 1 kylerisse users  90846 Feb 26 20:48 dhcp6-server.conf
-rw-r--r-- 1 kylerisse users   9457 Feb 26 20:48 prom.json
-rw-r--r-- 1 kylerisse users   7917 Feb 26 20:48 scale-wasgeht-config.json …
```

[READY] facts.inventory: add subcommand that generates a wasgeht config

---

switch-configuration/config/scripts/switch_template.pm

expansion.
Bug fixes to config generation
Bugy Configs
Configs now taste great and are less filling. The switches think they're yummy.
Mark 1 eyeball, ethernet cable, surgical tubing, and a yak.

URGENT: Fixed bugs in prefix interpretation (:: at end bad), Fixed bug with vlan

---

nix/nixos-configurations/core-slave/configuration.nix

Simplify and unify our DNS servers across configs. Masters for both. Remove the complexity of the master -> slave replication
- Slave replication for scale.lan zones
- run both bind severs as masters for scale.lan
- Applied and verified working against the slave:
```
$ dig @10.0.3.20 coreexpo.scale.lan +short
10.0.3.20
```

nixosConfigurations.coreSlave: bindMaster=enabled

---

switch-configuration/config/scripts/Loader.pm
switch-configuration/config/switchtypes

Minor patch to Loader (correct SFTP for local port)
Funeral for switch 9, Resurrection as switch 47
Unable to achieve Lazarus effect
Did not respond to painful stimuli
Switch 9 pronounced dead at 19:00 UTC March 4, 2025
SFTP tried to go to $HOSTNAME instead of local management interface even with -b and/or -l
Switch 47 reprovisioned to resurrect Rm209-210
SFTP goes to the right place now.
You put your yak hand in,
You put your yak hand out,
You put your yak hand in,
and shake it all about.
You do the Yakey Tacky and you turn yourself about.
That's what it's all about!

Minor patch to Loader and replacement of dead switch

---

facts/inventory.py

Got them the wrong way round
- Point to the wrong core severs for our names
- CNAMES all point to the right place
- Verified against both cores after applying these changes:
```
driver workspace $ dig @10.128.3.20 coremaster.scale.lan +short
coreexpo.scale.lan.
10.0.3.20
driver workspace $ dig @10.0.3.20 coremaster.scale.lan +short
coreconf.scale.lan.
10.128.3.20
driver workspace $ dig @10.128.3.20 coreslave.scale.lan +short
coreexpo.scale.lan.
10.0.3.20
driver workspace $ dig @10.0.3.20 coreslave.scale.lan +short
coreexpo.scale.lan.
10.0.3.20
checks.core passes:
```
$ nix build -L .#checks.x86_64-linux.core
```

facts.inventory: flipflop core* CNAMEs

---

nix/checks/loghost.nix
nix/nixos-modules/services/rsyslogd.nix

Add UDP support for rsyslog
- rsyslog not listening on UDP
- rsyslog listening on UDP
- `nix build --rebuild -L .#checks.x86_64-linux.loghost`
```
vm-test-run-loghost> (finished: must succeed: sleep 2, in 10.31 seconds)
vm-test-run-loghost> coremaster: must succeed: systemctl is-active syslog
vm-test-run-loghost> (finished: must succeed: systemctl is-active syslog, in 0.05 seconds)
vm-test-run-loghost> coremaster: must succeed: logger -n 127.0.0.1 -P 514 --tcp 'troyTCP'
vm-test-run-loghost> (finished: must succeed: logger -n 127.0.0.1 -P 514 --tcp 'troyTCP', in 0.04 seconds)
vm-test-run-loghost> coremaster: must succeed: cat /persist/rsyslog/**/root.log | grep troyTCP
vm-test-run-loghost> (finished: must succeed: cat /persist/rsyslog/**/root.log | grep troyTCP, in 0.04 seconds) …
```

[READY] rsyslog listen on UDP

---

facts/inventory.py

- Setting this to a string instead of uint8
- dhcp options were uint8
- dhcp options set to string
- Verified working on coreMaster

facts.inventory: set dhcp4 options to string

---

nix/nixos-modules/services/monitoring.nix

Fix the domain to be the one actually being accessed, add the recommended proxy settings, and add a location block for `/api/live` for Grafana.
Prior to this, Grafana was not working because the domain was set to localhost
We don't have a good way to test this right now, but plan to write checks in here once we can validate them.

Grafana fix

---

switch-configuration/config/scripts/switch_template.pm
switch-configuration/config/switchtypes

Added fe80::<num>/64 to me0 and vlan.[15]03 (depending on building. (First of 3 parts to #879, art of the possible)
Add fe80::<num> to me0 and vlan.[15]03 (depending on building) interfaces
Add NTP
Set timezone to UTC
None of that happened.
It's happening now.
SSH, hand configured bespoke switch, surgical tubing, lubricant, yak and 4 leather goddesses.
No yaks were harmed in the making of this PR. Cannot say the same for the leather goddesses.

Added NTP to configuration generator

---

nix/checks/default.nix

relates to: #894
This test is impure,  remove from default.nix for now
- tests pass

checks.signs: remove from default since impure

---

switch-configuration/config/scripts/switch_template.pm

Renumbering key servers means changing lots of weird little places in various bits of code. We're still finding them.
Whee!

More renumbering fallout

---

nix/nixos-modules/services/monitoring.nix

Add Prometheus scrape config for the wasgeht service's metrics
No metrics were collected
metrics will be stored in Prometheus and usable for Grafana dashboards
Running `:p nixosConfigurations.coreMaster.config.services.prometheus.scrapeConfigs` in the nix repl produces this snippet which shows the expected target is rendered:
```nix
static_configs = [
{
labels = { };
targets = [ "localhost:1982" ];
}
];
```

Add scraping of wasgeht

---

nix/nixos-configurations/core-slave/configuration.nix
nix/nixos-modules/services/monitoring.nix
nix/nixos-modules/services/snmp.yml

adds snmp_exporter and scrape jobs to prometheus
no data
data !
I was able to run the same config on my laptop, on the noc vlan and create graphs.
The snmp.yaml was generated using https://github.com/prometheus/snmp_exporter/tree/v0.28.0/generator paired down the just the juniper stats we care about

adds snmp_exporter and scrape jobs to prometheus

---

switch-configuration/config/scripts/switch_template.pm

https://www.juniper.net/documentation/us/en/software/junos/cos-security-devices/topics/concept/cos-forwarding-class-overview.html
Based on the info below and on manual testing, it appears that infra is the lowest priority prior right now. This inverts the order so that infra is highest priority.

Switch QoS order - it appears to be inverted

---

nix/nixos-modules/users/default.nix

Fix broken `master` by including `erikreinert` user entry
`nix build .#checks.x86_64-linux.core` passes with latest master

[READY] nix.modules.users: add missing erikreinert entry

---

nix/nixos-modules/services/signs.nix

Sunday morning changes to signs plus disable DHCPv6. https://github.com/socallinuxexpo/scale-signs/pull/76
Tested locally `podman run -p 8088:80 sarcasticadmin/scale-signs:8f6ed2f`

22x Signs DST

---

facts/inventory.py
nix/checks/core.nix

Fixes: https://github.com/socallinuxexpo/scale-network/issues/593
Revert: https://github.com/socallinuxexpo/scale-network/commit/37a7a87b079161e308c5eddfc791a3d6e46e0fb4
Sets the necessary dhcp6 option `ntp-server` (56) and sub-option according to documention in kea: https://kea.readthedocs.io/en/kea-3.0.0/arm/dhcp6-srv.html#ntp-server-suboptions
- Previously only dhcp4 had `ntp-servers` set
- ntp-servers are provided on both dhcp4 and dhcp6
- Confirmed vmTest for core are passing and that config contains expected values:
```
{
"Dhcp6": {
"valid-lifetime": 1440,
"min-valid-lifetime": 1440,
"max-valid-lifetime": 1440,
"interfaces-config": {
"interfaces": [
"@@INTERFACE@@",
"@@INTERFACE@@/@@SERVERADDRESS@@"
],
"service-sockets-max-retries": 5,
"service-sockets-retry-wait-time": 5000
}, …
```

facts.inventory: support dhcp6 ntp-server option

---

facts/inventory.py
nix/checks/core.nix
nix/packages/default.nix
nix/packages/dhcptest/package.nix

Fixes: #906
- Kea was only setting dhcp4 option 119 for search domain
- Kea needs to also add dhcp4 option 15 for completeness for the search domain
- Including a new package: `dhcptest` which allows for easy testing of DHCP options
- Testing options: `6,15,42,119`
- `nix run .#checks.x86_64-linux.core.config.test.driver -L`
- Testing the failure case (when option 15 is missing):
```
...
client1: must succeed: test ! -z "$(dhcptest --query --iface eth1 --quiet --request 6 --print-only 6)"
coremaster # [   26.993767] kea-dhcp4[856]: 2025-09-15 22:41:01.394 INFO  [kea-dhcp4.dhcp4/856.140139258443456] DHCP4_QUERY_LABEL received query: [hwtype=1 5e:7a:96:cf:4e:42], cid=[no info], tid=0x377d004e
client1: (finished: must succeed: test ! -z "$(dhcptest --query --iface eth1 --quiet --request 6 …
```

nixConfigurations.core: enable dhcp4 option 15

---

nix/checks/default.nix
nix/checks/router-border.nix
nix/checks/routers.nix
nix/nixos-configurations/router-border/README.md
nix/nixos-configurations/router-border/configuration.nix
nix/nixos-configurations/router-border/default.nix
nix/nixos-configurations/router-border/disko.nix
nix/nixos-configurations/router-border/hardware-configuration.nix
nix/nixos-modules/default.nix
nix/nixos-modules/routers/border.nix
nix/nixos-modules/routers/conference.nix
nix/nixos-modules/routers/default.nix
nix/nixos-modules/routers/expo.nix

Adds base layout for working on nixos based routers. I went with a structure of each router config lives in a nixos module (`nixos-modules/routers`) and that module can then be included in a nixos-configuration and a nixos test. This pr just contains the absolute basics of creating the modules with multiple interfaces and assigns some ips to those interfaces. Included is also a test that brings up all the routers and ensures they can ping each other.
This should be a good jumping off point for us to develop the more advanced features and config that we will need.

nix: Adds routers skeleton

---

nix/dev-shells/default.nix
nix/packages/default.nix
nix/packages/mac2eui64/mac2eui64.py
nix/packages/mac2eui64/package.nix

Supersedes: #955
Everything else releated to #955 was corrected as part of #972
We have had to generate the eui64 values before so this script should be kept for the next time we have to do such converstions. 
- No standard way of converting from mac to eui64
- `mac2eui64` is available in the default devShell
- confirming that `mac2eui64` works and is able to locate an existing entry in `facts/pi/pis.csv`
``` 
$ nix run .#mac2eui64 dc:a6:32:41:79:6a
dea6:32ff:fe41:796a
$ ag dea6:32ff:fe41:796a
facts/pi/pis.csv
2:pi4-001,dc:a6:32:41:79:6a,dea6:32ff:fe41:796a
```

[READY] nix.pkgs.mac2eui64: init
